---
permalink: online-help-96-97/concept_ldap_configuration_services.html 
sidebar: sidebar 
keywords: ldap, configuration, service, system, manager, online, help, storage, virtual, machine, ldap, client, window 
summary: È possibile utilizzare System Manager per gestire le configurazioni LDAP. 
---
= Gestione delle configurazioni LDAP con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per gestire le configurazioni LDAP, è possibile utilizzare Gestione di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti).



== Modificare i client LDAP attivi

È possibile utilizzare System Manager per associare un client LDAP attivo a una macchina virtuale di storage (SVM), che consente di utilizzare LDAP come servizio di nomi o per la mappatura dei nomi.

.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM, quindi fare clic su *SVM Settings* (Impostazioni SVM).
. Nel riquadro *servizi*, fare clic su *Configurazione LDAP*.
. Nella finestra *Configurazione LDAP*, fare clic su *Modifica*.
. Nella finestra di dialogo *Client LDAP attivo*, selezionare il client LDAP che si desidera modificare ed eseguire le seguenti operazioni:
+
** Modificare i server di dominio Active Directory.
** Modificare i server Active Directory preferiti.


. Fare clic su *OK*.
. Verificare che le modifiche apportate siano aggiornate nella finestra *Configurazione LDAP*.




== Eliminare i client LDAP attivi

È possibile utilizzare System Manager per eliminare un client LDAP attivo quando non si desidera associare una macchina virtuale di storage (SVM).

.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM, quindi fare clic su *SVM Settings* (Impostazioni SVM).
. Fare clic sulla scheda *Impostazioni SVM*.
. Nel riquadro *servizi*, fare clic su *Configurazione LDAP*.
. Fare clic su *Delete* (Elimina).
. Selezionare la casella di controllo di conferma, quindi fare clic su *Elimina*.




== Finestra di configurazione LDAP

È possibile utilizzare la finestra Configurazione LDAP per modificare o eliminare i client LDAP attivi a livello di SVM (Storage Virtual Machine).



=== Pulsanti di comando

* *Modifica*
+
Apre la finestra di dialogo Active LDAP Client, che consente di modificare le proprietà del client LDAP attivo, ad esempio i server di dominio Active Directory e i server Active Directory preferiti.

* *Elimina*
+
Apre la finestra di dialogo Delete Active LDAP Client (Elimina client LDAP attivo), che consente di eliminare il client LDAP attivo.

* *Aggiorna*
+
Aggiorna le informazioni nella finestra.





=== Area di configurazione LDAP

Visualizza i dettagli sul client LDAP attivo.

* *Nome client LDAP*
+
Visualizza il nome del client LDAP attivo.

* *Server di dominio Active Directory*
+
Visualizza il dominio Active Directory per il client LDAP attivo.

* *Server Active Directory preferiti*
+
Visualizza il server Active Directory preferito per il client LDAP attivo.


