---
permalink: online-help-96-97/concept_storage_recommendations_for_creating_aggregates.html 
sidebar: sidebar 
keywords: storage, recommendations, create, aggregate, system, manager, online, help 
summary: 'A partire da System Manager 9.4, è possibile creare aggregati in base alle raccomandazioni sullo storage. Tuttavia, è necessario determinare se la creazione di aggregati in base alle raccomandazioni sullo storage è supportata nel proprio ambiente. Se l"ambiente in uso non supporta la creazione di aggregati in base alle raccomandazioni sullo storage, è necessario decidere la policy RAID e la configurazione del disco, quindi creare gli aggregati manualmente.' 
---
= Consigli per lo storage per la creazione di aggregati con System Manager - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da System Manager 9.4, è possibile creare aggregati in base alle raccomandazioni sullo storage. Tuttavia, è necessario determinare se la creazione di aggregati in base alle raccomandazioni sullo storage è supportata nel proprio ambiente. Se l'ambiente in uso non supporta la creazione di aggregati in base alle raccomandazioni sullo storage, è necessario decidere la policy RAID e la configurazione del disco, quindi creare gli aggregati manualmente.

System Manager analizza i dischi spare disponibili nel cluster e genera un consiglio su come utilizzare i dischi spare per creare aggregati in base alle Best practice. System Manager visualizza il riepilogo degli aggregati consigliati, inclusi i nomi e le dimensioni utilizzabili.

In molti casi, la raccomandazione relativa allo storage sarà ottimale per il tuo ambiente. Tuttavia, se nel cluster è in esecuzione ONTAP 9.3 o versioni precedenti o se l'ambiente include le seguenti configurazioni, è necessario creare gli aggregati manualmente:

* Aggregati che utilizzano LUN di array di terze parti
* Dischi virtuali con Cloud Volumes ONTAP o ONTAP Select
* Configurazioni MetroCluster
* Funzionalità SyncMirror
* Dischi MSATA
* Aggregati di Flash Pool
* Al nodo sono collegati diversi tipi o dimensioni di dischi


Inoltre, se nell'ambiente sono presenti le seguenti condizioni di disco, è necessario correggere le condizioni del disco prima di utilizzare le raccomandazioni di storage per creare aggregati:

* Dischi mancanti
* Fluttuazione nei numeri dei dischi spare
* Dischi non assegnati
* Parti di ricambio non azzerate (per le versioni di ONTAP precedenti alla 9.6)
* Dischi sottoposti a test di manutenzione


*Informazioni correlate*

https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["Gestione di dischi e aggregati"]

xref:task_zeroing_disks.adoc[Azzeramento dei dischi spare]
