---
permalink: online-help-96-97/concept_efficiency_policies.html 
sidebar: sidebar 
keywords: efficiency, policy, system, manager, create, edit, delete, online, help, flexvol, window 
summary: È possibile utilizzare System Manager per creare, modificare ed eliminare le policy di efficienza. 
---
= Gestione delle policy di efficienza con System Manager - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per creare, modificare ed eliminare le policy di efficienza.



== Aggiungi policy di efficienza

È possibile utilizzare System Manager per aggiungere policy di efficienza per l'esecuzione dell'operazione di deduplica su un volume in base a una pianificazione specifica o quando la modifica dei dati del volume raggiunge un valore di soglia specificato.

.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM, quindi fare clic su *SVM Settings* (Impostazioni SVM).
. Nel riquadro *Policy*, fare clic su *Efficiency Policies*.
. Fare clic su *Aggiungi*, quindi specificare il nome del criterio.
. Specificare come eseguire la policy di efficienza dello storage:
+
** Selezionare *Schedule*, quindi specificare il nome del programma e i dettagli del programma.
+
Se necessario, è possibile specificare la durata massima del run-time della policy di efficienza.

** Selezionare *ChangeLog Threshold* e specificare il valore di soglia (in percentuale) per la modifica dei dati del volume.


. *Opzionale:* selezionare la casella di controllo *Imposta policy QoS su background* per ridurre l'impatto delle performance sulle operazioni del client.
. Fare clic su *Aggiungi*.




== Modificare le policy di efficienza

È possibile utilizzare System Manager per modificare gli attributi di un criterio di efficienza, ad esempio il nome del criterio, il nome del programma e il runtime massimo.

.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM, quindi fare clic su *SVM Settings* (Impostazioni SVM).
. Nel riquadro *Policy*, fare clic su *Efficiency Policies*.
. Nella finestra *Efficiency Policies*, selezionare il criterio che si desidera modificare, quindi fare clic su *Edit* (Modifica).
. Nella finestra di dialogo *Edit Efficiency Policy* (Modifica policy di efficienza), apportare le modifiche necessarie.
. Fare clic su *Save* (Salva).




== Eliminare le policy di efficienza

È possibile utilizzare System Managerper eliminare una policy di efficienza che non è più necessaria.

.Prima di iniziare
La policy di efficienza deve essere disattivata.

.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM, quindi fare clic su *SVM Settings* (Impostazioni SVM).
. Nel riquadro *Policy*, fare clic su *Efficiency Policies*.
. Selezionare la policy di efficienza che si desidera eliminare, quindi fare clic su *Delete* (Elimina).
. Selezionare la casella di controllo di conferma, quindi fare clic su *Elimina*.




== Attivare o disattivare le policy di efficienza

È possibile utilizzare System Manager per attivare o disattivare una policy di efficienza.

.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM, quindi fare clic su *SVM Settings* (Impostazioni SVM).
. Nel riquadro *Policy*, fare clic su *Efficiency Policies*.
. Selezionare una o più policy di efficienza che si desidera attivare o disattivare.
. Fare clic su *Status* > *Enable* o *Status* > *Disable*, secondo necessità.
. Se si disattiva un criterio di efficienza, selezionare la casella di controllo di conferma, quindi fare clic su *OK*.




== Che cos'è una policy di efficienza

Una policy di efficienza è una pianificazione dei processi per un'operazione di deduplica su un volume FlexVol.

È possibile eseguire la deduplica su un volume FlexVol programmando l'avvio delle operazioni a un'ora specifica o specificando che le operazioni vengono attivate in caso di superamento di una percentuale di soglia. È possibile pianificare un'operazione di deduplica creando pianificazioni di lavoro che sono incluse nelle policy di efficienza. Le policy di efficienza dei volumi supportano solo le pianificazioni dei processi di tipo cron. In alternativa, è possibile specificare una percentuale di soglia. Quando i nuovi dati superano la percentuale specificata, viene avviata l'operazione di deduplica.



== Comprensione delle policy di efficienza predefinite

È possibile configurare un volume con policy di efficienza per ottenere ulteriori risparmi di spazio. È possibile configurare un volume per eseguire la compressione inline senza un'operazione di efficienza in background pianificata o avviata manualmente configurata sul volume.

Quando si crea una SVM, le seguenti policy di efficienza vengono create automaticamente e non possono essere eliminate:

* Predefinito
+
È possibile configurare un volume con la policy di efficienza per eseguire le operazioni di deduplica pianificate sul volume.

* Solo inline
+
È possibile configurare un volume con il criterio di efficienza solo inline e attivare la compressione inline, per eseguire la compressione inline sul volume senza alcuna operazione di efficienza in background pianificata o avviata manualmente.



Per ulteriori informazioni sui criteri di efficienza predefiniti e inline-only, consulta le pagine man.



== Finestra Efficiency Policies

È possibile utilizzare la finestra Efficiency Policies per creare, visualizzare e gestire informazioni sulle policy di efficienza.



=== Pulsanti di comando

* *Aggiungi*
+
Apre la finestra di dialogo Add Efficiency Policy (Aggiungi policy di efficienza), che consente di eseguire un'operazione di deduplica su un volume per una durata specificata (in base alla pianificazione) o quando la modifica dei dati del volume raggiunge un valore di soglia specificato (in base alla soglia).

* *Modifica*
+
Apre la finestra di dialogo Edit Efficiency Policy (Modifica policy di efficienza), che consente di modificare la pianificazione, il valore di soglia, il tipo di QoS e il tempo di esecuzione massimo per un'operazione di deduplica.

* *Elimina*
+
Apre la finestra di dialogo Delete Efficiency Policy (Elimina policy di efficienza), che consente di eliminare la policy di efficienza selezionata.

* *Stato*
+
Aprire un menu a discesa che fornisce le opzioni per attivare o disattivare il criterio di efficienza selezionato.

* *Aggiorna*
+
Aggiorna le informazioni nella finestra.





=== Elenco delle policy di efficienza

* *Auto*
+
Specifica che la deduplica viene eseguita continuamente in background. Questo criterio viene impostato per tutti i volumi appena creati e per tutti i volumi aggiornati che non sono stati configurati manualmente per la deduplica in background. Se si modifica il criterio in "`default`" o in qualsiasi altro criterio, il criterio "`auto`" viene disattivato.

+
Se un volume si sposta da un sistema non AFF a un sistema AFF, il criterio "`auto`" viene attivato sul nodo di destinazione per impostazione predefinita. Se un volume si sposta da un nodo AFF a un nodo non AFF, il criterio "`auto`" sul nodo di destinazione viene sostituito per impostazione predefinita dal criterio "`inline-only`".

* *Policy*
+
Specifica il nome di una policy di efficienza.

* *Stato*
+
Specifica lo stato di una policy di efficienza. Lo stato può essere uno dei seguenti:

+
** Attivato
+
Specifica che la policy di efficienza può essere assegnata a un'operazione di deduplica.

** Disattivato
+
Specifica che la policy di efficienza è disattivata. È possibile attivare il criterio utilizzando il menu a discesa status (Stato) e assegnarlo successivamente a un'operazione di deduplica.



* *Esegui da*
+
Specifica se la policy di efficienza dello storage viene eseguita in base a una pianificazione o a un valore di soglia (modifica soglia log).

* *Policy QoS*
+
Specifica il tipo di QoS per la policy di efficienza dello storage. Il tipo di QoS può essere uno dei seguenti:

+
** Sfondo
+
Specifica che il criterio QoS è in esecuzione in background, riducendo il potenziale impatto delle performance sulle operazioni del client.

** Best-effort
+
Specifica che il criterio QoS viene eseguito con il massimo sforzo, consentendo di massimizzare l'utilizzo delle risorse di sistema.



* *Durata massima*
+
Specifica la durata massima del run-time di una policy di efficienza. Se questo valore non viene specificato, il criterio di efficienza viene eseguito fino al completamento dell'operazione.





=== Area dei dettagli

L'area sotto l'elenco dei criteri di efficienza visualizza informazioni aggiuntive sulla policy di efficienza selezionata, tra cui il nome della pianificazione e i dettagli della pianificazione per una policy basata sulla pianificazione e il valore di soglia per una policy basata sulla soglia.
