---
permalink: online-help-96-97/concept_cifs_protocol.html 
sidebar: sidebar 
keywords: cif, protocol, system, manager, enable, configure, server, client, file, cluster, online, help, set up, general, properties, edit 
summary: È possibile utilizzare System Manager per abilitare e configurare i server CIFS in modo da consentire ai client CIFS di accedere ai file nel cluster. 
---
= Configurare il protocollo CIFS con System Manager - ONTAP 9,7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per abilitare e configurare i server CIFS in modo da consentire ai client CIFS di accedere ai file nel cluster.



== Configurare CIFS

È possibile utilizzare System Manager per abilitare e configurare i server CIFS in modo da consentire ai client CIFS di accedere ai file sul cluster.

.Prima di iniziare
* La licenza CIFS deve essere installata sul sistema storage.
* Durante la configurazione di CIFS nel dominio Active Directory, devono essere soddisfatti i seguenti requisiti:
+
** Il DNS deve essere attivato e configurato correttamente.
** Il sistema storage deve essere in grado di comunicare con il controller di dominio utilizzando il nome di dominio completo (FQDN).
** La differenza di tempo (disallineamento del clock) tra il cluster e il controller di dominio non deve superare i cinque minuti.


* Se CIFS è l'unico protocollo configurato sulla macchina virtuale di storage (SVM), devono essere soddisfatti i seguenti requisiti:
+
** Lo stile di protezione del volume root deve essere NTFS.
+
Per impostazione predefinita, System Manager imposta lo stile di protezione come UNIX.

** L'accesso superutente deve essere impostato su `Any` Per il protocollo CIFS.




.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM, quindi fare clic su *SVM Settings* (Impostazioni SVM).
. Nella scheda *Configurazione*, fare clic su *Configura*.
. Nella scheda *General* della finestra di dialogo *CIFS Server Setup*, specificare il nome NetBIOS e i dettagli del dominio Active Directory.
. Fare clic sulla scheda *Opzioni*, quindi eseguire le seguenti operazioni:
+
** Nell'area delle impostazioni SMB, selezionare o deselezionare la casella di controllo SMB Signing (Firma SMB) e la casella di controllo SMB Encryption (crittografia SMB), secondo necessità.
** Specificare l'utente UNIX predefinito.
** Nell'area WINS Servers (Server WINS), aggiungere l'indirizzo IP richiesto.


. Fare clic su *Set up* (Configura).




== Modificare le proprietà generali di CIFS

È possibile modificare le proprietà generali di CIFS, ad esempio l'utente UNIX predefinito e l'utente Windows predefinito, utilizzando System Manager. È inoltre possibile attivare o disattivare la firma SMB per il server CIFS.

.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM, quindi fare clic su *SVM Settings* (Impostazioni SVM).
. Nella scheda *Configurazione*, fare clic su *Opzioni*.
. Nella finestra di dialogo *Opzioni CIFS*, modificare le seguenti proprietà del server CIFS, come richiesto:
+
** Utente UNIX
** Utente Windows
** Indirizzo IP
** Attiva o disattiva la firma SMB
+
L'abilitazione della firma SMB impedisce la compromissione dei dati. Tuttavia, si potrebbe riscontrare un peggioramento delle performance sotto forma di un maggiore utilizzo della CPU sia sui client che sul server, anche se il traffico di rete rimane invariato. È possibile disattivare la firma SMB su qualsiasi client Windows che non richieda protezione contro gli attacchi di replay.

+
Per informazioni sulla disattivazione della firma SMB sui client Windows, consultare la documentazione di Microsoft Windows.

** Attiva o disattiva la crittografia SMB 3.0
+
È necessario abilitare SMB Multichannel per stabilire più canali tra una sessione SMB 3.0 e le connessioni di trasporto.



. Fare clic su *Salva* o *Salva e chiudi*.


*Informazioni correlate*

xref:task_creating_cifs_share.adoc[Creazione di una condivisione CIFS]

xref:reference_cifs_window.adoc[Finestra CIFS]

xref:task_editing_volume_properties.adoc[Modifica delle proprietà del volume]

xref:task_modifying_export_policy_rules.adoc[Modifica delle regole dei criteri di esportazione]

https://docs.netapp.com/us-en/ontap/smb-admin/index.html["Gestione SMB/CIFS"]
