---
permalink: online-help-96-97/concept_configuration_update.html 
sidebar: sidebar 
keywords: configuration, update, system, manager, administration, detail, storage, virtual, machine, svm, online, help, window, tab, node, command, button 
summary: 'È possibile utilizzare System Manager per configurare i dettagli di amministrazione delle macchine virtuali di storage (SVM).' 
---
= Aggiornamento della configurazione con Gestore di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per configurare i dettagli di amministrazione delle macchine virtuali di storage (SVM).



== Configurare i dettagli di amministrazione di una SVM

È possibile utilizzare System Manager per configurare rapidamente i dettagli di amministrazione di astorage Virtual Machine (SVM). Facoltativamente, è possibile delegare l'amministrazione di SVM agli amministratori di SVM.

.A proposito di questa attività
In qualità di amministratore di SVM, non è possibile utilizzare System Manager per gestire le SVM delegate. È possibile gestire solo SVMsutilizzando l'interfaccia della riga di comando (CLI).

.Fasi
. Fare clic su *Configuration* > *Cluster* > *Configuration Updates*.
. Nella scheda *SVM*, selezionare il nodo, quindi fare clic su *Configure Administration Details*.
. Nella sezione *Dettagli amministratore*, impostare una password per `vsadmin` account utente.
. Se si desidera un LIF dedicato per la gestione SVM, selezionare *Crea un LIF per la gestione SVM*, quindi specificare i dettagli di rete.
+
Per i protocolli SAN è richiesta una LIF di gestione SVM dedicata, in cui i protocolli di gestione e dati non possono condividere la stessa LIF. Le LIF di gestione SVM possono essere create solo sulle porte dati.

. Specificare i dettagli di rete:
+
|===
| Se si desidera... | Quindi... 


 a| 
Specificare l'indirizzo IP utilizzando una subnet
 a| 
.. Selezionare *utilizzando una subnet*.
.. Nella finestra di dialogo Add Details (Aggiungi dettagli), selezionare la subnet da cui assegnare l'indirizzo IP.
+
Per le LIF intercluster, vengono visualizzate solo le subnet associate all'IPSpace selezionato.

.. Se si desidera assegnare un indirizzo IP specifico all'interfaccia, selezionare *Usa un indirizzo IP specifico*, quindi digitare l'indirizzo IP.
+
L'indirizzo IP specificato viene aggiunto alla subnet se tale indirizzo IP non è già presente nell'intervallo di sottorete.

.. Fare clic su *OK*.




 a| 
Specificare manualmente l'indirizzo IP senza utilizzare una subnet
 a| 
.. Selezionare *senza subnet*.
.. Nella finestra di dialogo Add Details (Aggiungi dettagli), attenersi alla seguente procedura:
+
... Specificare l'indirizzo IP e la maschera o il prefisso di rete.
... Facoltativo: Specificare il gateway.
+
Il campo di destinazione viene popolato con il valore predefinito in base alla famiglia dell'indirizzo IP.

... Se non si desidera utilizzare il valore predefinito, specificare un nuovo valore di destinazione.
Se non esiste un percorso, viene creato automaticamente un nuovo percorso in base al gateway e alla destinazione.


.. Fare clic su *OK*.


|===
. Specificare una porta per creare una LIF dati:
+
.. Fare clic su *Sfoglia*.
.. Nella finestra di dialogo *Seleziona porta di rete o adattatore*, selezionare una porta, quindi fare clic su *OK*.






== Finestra di aggiornamento della configurazione

È possibile utilizzare la finestra Configuration Updates (aggiornamenti configurazione) per aggiornare i dettagli di configurazione del cluster, della SVM (Storage Virtual Machine) e dei nodi.



=== Schede

* *Nodi*
+
Consente di configurare i dettagli del nodo.

* *SVM*
+
Consente di configurare i dettagli della SVM.





=== Scheda nodi



=== Pulsanti di comando

* *Modifica nome nodo*
+
Apre la finestra di dialogo Edit Node Name (Modifica nome nodo), che consente di modificare il nome del nodo.

* *Crea LIF di gestione dei nodi*
+
Apre la finestra di dialogo Create Node-management LIF (Crea LIF di gestione dei nodi), che consente di creare una LIF di gestione dei nodi per la gestione di un nodo specifico.

* *Modifica AutoSupport*
+
Apre la finestra di dialogo Modifica impostazioni AutoSupport, che consente di specificare un indirizzo e-mail da cui inviare le notifiche e-mail e di aggiungere più indirizzi e-mail dei nomi host.





=== Scheda SVM



=== Pulsante di comando

* *Configura dettagli amministrazione*
+
Apre la finestra di dialogo Configure Administration Details (Configura dettagli di amministrazione), che consente di configurare i dettagli di amministrazione di SVM.



*Informazioni correlate*

xref:task_creating_cluster.adoc[Creazione di un cluster]

xref:task_setting_up_network_when_ip_address_range_is_disabled.adoc[Impostazione di una rete quando un intervallo di indirizzi IP è disattivato]
