---
permalink: online-help-96-97/concept_how_data_ontap_name_service_switch_configuration_works.html 
sidebar: sidebar 
keywords: ontap, name, service, switch, configuration, works, unix, system, online, help 
summary: 'ONTAP memorizza le informazioni di configurazione del name service in una tabella equivalente al file /etc/nsswitch.conf nei sistemi UNIX. È necessario comprendere la funzione della tabella e il modo in cui ONTAP la utilizza in modo da poterla configurare in modo appropriato per l"ambiente in uso.' 
---
= Informazioni sulla configurazione dello switch ONTAP name service in Gestione sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) memorizza le informazioni di configurazione del servizio dei nomi in una tabella equivalente a `/etc/nsswitch.conf` File su sistemi UNIX. È necessario comprendere la funzione della tabella e il modo in cui ONTAP la utilizza in modo da poterla configurare in modo appropriato per l'ambiente in uso.

La tabella ONTAP name service switch determina le origini del servizio di nomi che ONTAP consulta per recuperare le informazioni relative a un determinato tipo di informazioni sul servizio di nomi. ONTAP gestisce una tabella di switch del name service separata per ogni SVM.



== Tipi di database

La tabella memorizza un elenco di name service separato per ciascuno dei seguenti tipi di database:

|===
| Tipo di database | Definisce le origini del servizio nome per... | Le origini valide sono... 


 a| 
host
 a| 
Conversione dei nomi host in indirizzi IP
 a| 
file, dns



 a| 
gruppo
 a| 
Ricerca di informazioni sul gruppo di utenti
 a| 
file, nis, ldap



 a| 
password
 a| 
Ricerca delle informazioni dell'utente
 a| 
file, nis, ldap



 a| 
netgroup
 a| 
Ricerca di informazioni sul netgroup
 a| 
file, nis, ldap



 a| 
mappa dei nomi
 a| 
Mappatura dei nomi utente
 a| 
file, ldap

|===


== Tipi di origine

Le origini specificano quale nome di origine del servizio utilizzare per recuperare le informazioni appropriate.

|===
| Specifica tipo di origine... | Per cercare informazioni in... | Gestito dalle famiglie di comandi... 


 a| 
file
 a| 
File di origine locali
 a| 
`vserver services name-service unix-user`

`vserver services name-service unix-group`

`vserver services name-service netgroup`

`vserver services name-service dns hosts`



 a| 
nis
 a| 
Server NIS esterni come specificato nella configurazione del dominio NIS di SVM
 a| 
`vserver services name-service nis-domain`



 a| 
ldap
 a| 
Server LDAP esterni come specificato nella configurazione del client LDAP di SVM
 a| 
`vserver services name-service ldap`



 a| 
dns
 a| 
Server DNS esterni come specificato nella configurazione DNS di SVM
 a| 
`vserver services name-service dns`

|===
Anche se si prevede di utilizzare NIS o LDAP per l'accesso ai dati e l'autenticazione dell'amministrazione SVM, è comunque necessario includere `files` E configurare gli utenti locali come fallback nel caso in cui l'autenticazione NIS o LDAP non riesca.

*Informazioni correlate*

xref:task_editing_svm_settings.adoc[Modifica delle impostazioni SVM]
