---
permalink: online-help-96-97/concept_lun_multiprotocol_type_guidelines.html 
sidebar: sidebar 
keywords: guidelines, lun, multiprotocol, type, operating, system, host, layout, data, minimum, maximum, size, online, help 
summary: 'Il tipo di multiprotocollo LUN, o tipo di sistema operativo, specifica il sistema operativo dell"host che accede al LUN. Determina inoltre il layout dei dati sul LUN e le dimensioni minime e massime del LUN.' 
---
= Linee guida per l'utilizzo del tipo multiprotocollo LUN in Gestione sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti), il tipo di multiprotocollo LUN o di sistema operativo specifica il sistema operativo dell'host che accede al LUN. Determina inoltre il layout dei dati sul LUN e le dimensioni minime e massime del LUN.

[NOTE]
====
Non tutte le versioni di ONTAP supportano tutti i tipi di LUN multiprotocollo. Per le informazioni più recenti, consulta il tool Interoperability Matrix.

====
La seguente tabella descrive i valori del tipo multiprotocollo LUN e le linee guida per l'utilizzo di ciascun tipo:

|===
| Tipo multiprotocollo LUN | Quando utilizzare 


 a| 
AIX
 a| 
Se il sistema operativo host è AIX.



 a| 
HP-UX
 a| 
Se il sistema operativo host in uso è HP-UX.



 a| 
Hyper-V.
 a| 
Se si utilizza Windows Server 2008 o Windows Server 2012 Hyper-V e le LUN contengono dischi rigidi virtuali (VHD). Se si utilizza hyper_v per il proprio tipo di LUN, si consiglia di utilizzare hyper_v anche per il tipo di sistema operativo igroup.

[NOTE]
====
Per i LUN raw, è possibile utilizzare il tipo di sistema operativo figlio utilizzato dal tipo multiprotocollo LUN.

====


 a| 
Linux
 a| 
Se il sistema operativo host è Linux.



 a| 
NetWare
 a| 
Se il sistema operativo host in uso è NetWare.



 a| 
OpenVMS
 a| 
Se il sistema operativo host è OpenVMS.



 a| 
Solaris
 a| 
Se il sistema operativo host in uso è Solaris e non si utilizzano le etichette EFI di Solaris.



 a| 
EFI di Solaris
 a| 
Se si utilizzano le etichette EFI di Solaris.

[NOTE]
====
L'utilizzo di qualsiasi altro tipo di LUN multiprotocollo con le etichette di Solaris EFI potrebbe causare problemi di disallineamento del LUN.

====


 a| 
VMware
 a| 
Se si utilizza un server ESX e le LUN verranno configurate con VMFS.

[NOTE]
====
Se si configurano i LUN con RDM, è possibile utilizzare il sistema operativo guest come tipo di multiprotocollo LUN.

====


 a| 
MBR di Windows 2003
 a| 
Se il sistema operativo host in uso è Windows Server 2003 con il metodo di partizione MBR.



 a| 
GPT di Windows 2003
 a| 
Se si desidera utilizzare il metodo di partizione GPT e l'host è in grado di utilizzarlo. Windows Server 2003, Service Pack 1 e versioni successive sono in grado di utilizzare il metodo di partizione GPT e tutte le versioni a 64 bit di Windows lo supportano.



 a| 
Windows 2008 o versione successiva
 a| 
Se il sistema operativo host in uso è Windows Server 2008 o versione successiva, sono supportati entrambi i metodi di partizione MBR e GPT.



 a| 
Xen
 a| 
Se si utilizza Xen e le LUN saranno configurate con Linux LVM con Dom0.

[NOTE]
====
Per le LUN raw, è possibile utilizzare il tipo di sistema operativo guest utilizzato dal tipo multiprotocollo LUN.

====
|===
*Informazioni correlate*

xref:task_creating_luns.adoc[Creazione di LUN]

https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilità NetApp"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1148981["Guida all'installazione e alla configurazione di Solaris host Utilities 6,1"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1148983["Guida di riferimento ai comandi rapidi di Solaris host Utilities 6.1"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1148982["Note sulla versione di Solaris host Utilities 6.1"]
