---
permalink: online-help-96-97/concept_shares.html 
sidebar: sidebar 
keywords: online, help, share, system, manager, qtress, cifs, create, edit, manage, share, access, stop, home, directory, configure, smb 
summary: È possibile utilizzare System Manager per creare, modificare e gestire le condivisioni. 
---
= Gestione delle condivisioni con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 


Per creare, modificare e gestire le condivisioni, è possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti).



== Creare una condivisione CIFS

È possibile utilizzare System Manager per creare una condivisione CIFS che consenta di specificare la cartella, il qtree o il volume a cui gli utenti CIFS possono accedere.

.Prima di iniziare
È necessario aver installato la licenza CIFS prima di configurare e avviare CIFS.

.Fasi
. Fare clic su *Storage* > *Shares*.
. Dal menu a discesa nel campo *SVM*, selezionare la SVM su cui si desidera creare una condivisione CIFS.
. Fare clic su *Create Share* (Crea condivisione).
. Nella finestra *Create Share* (Crea condivisione), fare clic su *Browse* (Sfoglia), quindi selezionare la cartella, il qtree o il volume da condividere.
. Specificare un nome per la nuova condivisione CIFS.
. *Opzionale:* selezionare la casella di controllo *attiva disponibilità continua per Hyper-V e SQL* per consentire ai client che supportano SMB 3.0 e versioni successive di aprire i file in modo persistente durante le operazioni senza interruzioni.
+
I file aperti con questa opzione sono protetti da eventi di interruzione come failover, giveback e migrazione LIF.

+
A partire da System Manager 9.6, la disponibilità continua è supportata per i volumi FlexGroup.

. Selezionare la casella di controllo *Crittografa i dati durante l'accesso alla condivisione* per attivare la crittografia SMB 3.0.
. Fornire una descrizione o un commento per la condivisione, quindi fare clic su *Crea*.


.Risultati
La condivisione CIFS viene creata con le autorizzazioni di accesso impostate su "`controllo completo per tutti`" nel gruppo.



== Interrompere l'accesso alla condivisione

È possibile utilizzare System Manager per interrompere una condivisione quando si desidera rimuovere l'accesso di rete condiviso a una cartella, a un qtree o a un volume.

.Prima di iniziare
È necessario aver installato la licenza CIFS.

.Fasi
. Fare clic su *Storage* > *Shares*.
. Dal menu a discesa nel campo *SVM*, selezionare la SVM in cui risiede la condivisione CIFS che si desidera arrestare.
. Dall'elenco delle condivisioni, selezionare la condivisione che si desidera interrompere, quindi fare clic su *Interrompi condivisione*.
. Selezionare la casella di controllo di conferma, quindi fare clic su *Stop*.
. Verificare che la condivisione non sia più elencata nella finestra *Shares*.




== Creare condivisioni home directory

È possibile utilizzare System Manager per creare una condivisione home directory e gestire i percorsi di ricerca home directory.

.Prima di iniziare
CIFS deve essere configurato e avviato.

.Fasi
. Fare clic su *Storage* > *Shares*.
. Fare clic su *Create Home Directory*, quindi fornire le informazioni sul modello che determinano il modo in cui un utente viene mappato a una directory.
. Fare clic su *Create* (Crea).
. Verificare che la home directory creata sia elencata nella finestra *shares*.




== Modificare le impostazioni di condivisione

È possibile utilizzare System Manager per modificare le impostazioni di una condivisione, ad esempio le impostazioni dei collegamenti simbolici, i permessi di accesso alla condivisione di utenti o gruppi e il tipo di accesso alla condivisione. È inoltre possibile attivare o disattivare la disponibilità continua di una condivisione su Hyper-V e attivare o disattivare l'enumerazione basata sull'accesso (ABE). A partire da System Manager 9.6, la disponibilità continua è supportata per i volumi FlexGroup.

.Fasi
. Fare clic su *Storage* > *Shares*.
. Selezionare la condivisione che si desidera modificare dall'elenco delle condivisioni, quindi fare clic su *Modifica*.
. Nella finestra di dialogo *Modifica impostazioni di condivisione*, modificare le impostazioni di condivisione come richiesto:
+
.. Nella scheda *Generale*, attivare la disponibilità continua di una condivisione su Hyper-V.
+
L'attivazione della disponibilità continua consente a SMB 3.0 e ai client che supportano SMB 3.0 di aprire i file in modo persistente durante le operazioni senza interruzioni. I file aperti in modo persistente sono protetti da eventi di interruzione come failover, giveback e migrazione LIF.

.. Nella scheda *Permissions*, aggiungere utenti o gruppi, quindi assegnare le autorizzazioni per specificare il tipo di accesso.
.. Nella scheda *Opzioni*, selezionare le opzioni desiderate.


. Fare clic su *Save and Close* (Salva e chiudi).
. Verificare le modifiche apportate alla condivisione selezionata nella finestra *condivisioni*.




== In che modo ONTAP abilita le home directory dinamiche

Le home directory di ONTAP consentono di configurare una condivisione SMB che viene mappata a diverse directory in base all'utente che si connette ad essa e a una serie di variabili. Invece di creare condivisioni separate per ciascun utente, è possibile configurare una condivisione con alcuni parametri della home directory per definire la relazione di un utente tra un punto di ingresso (la condivisione) e la home directory (una directory sulla SVM).

Un utente che ha effettuato l'accesso come utente ospite non dispone di una home directory e non può accedere alle home directory di altri utenti. Esistono quattro variabili che determinano il modo in cui un utente viene mappato a una directory:

* *Nome condivisione*
+
Si tratta del nome della condivisione creata a cui l'utente si connette. È necessario impostare la proprietà home directory per questa condivisione.

+
Il nome della condivisione può utilizzare i seguenti nomi dinamici:

+
** `%w` (Il nome utente Windows dell'utente)
** `%d` (Il nome di dominio Windows dell'utente)
** `%u` (Il nome utente UNIX mappato dell'utente)


+
Per rendere unico il nome di condivisione in tutte le home directory, il nome di condivisione deve contenere/`%w` o il `%u` variabile. Il nome della condivisione può contenere entrambi `%d` e a./`%w` variabile (ad esempio, `%d`/`%w`), oppure il nome della condivisione può contenere una porzione statica e una porzione variabile (ad esempio, home_/`%w`).

* *Percorso di condivisione*
+
Si tratta del percorso relativo, definito dalla condivisione e quindi associato a uno dei nomi di condivisione, che viene aggiunto a ciascun percorso di ricerca per generare l'intero percorso della home directory dell'utente dalla directory principale della SVM. Può essere statico (ad esempio, `home`), dinamico (ad esempio, `%w`), o una combinazione dei due (ad esempio, `eng/%w`).

* *Percorsi di ricerca*
+
Questo è l'insieme di percorsi assoluti dalla directory principale di SVM che si specifica che dirige la ricerca di home directory in ONTAP. È possibile specificare uno o più percorsi di ricerca utilizzando `vserver cifs home-directory search-path add` comando. Se si specificano più percorsi di ricerca, ONTAP li prova nell'ordine specificato fino a trovare un percorso valido.

* *Directory*
+
Questa è la home directory dell'utente creata per l'utente. Il nome della directory è generalmente il nome dell'utente. È necessario creare la home directory in una delle directory definite dai percorsi di ricerca.



Ad esempio, considerare la seguente configurazione:

* Utente: John Smith
* Dominio utente: acme
* Nome utente: Jsmith
* Nome SVM: vs1
* Nome di condivisione della home directory n. 1: home_ `%w` - percorso di condivisione: `%w`
* Nome condivisione home directory n. 2: `%w` - percorso di condivisione: `%d/%w`
* Percorso di ricerca n. 1: `/vol0home/home`
* Percorso di ricerca n. 2: `/vol1home/home`
* Percorso di ricerca n. 3: `/vol2home/home`
* Home directory: `/vol1home/home/jsmith`


Scenario 1: L'utente si connette a. `\\vs1\home_jsmith`. Corrisponde al primo nome di condivisione della home directory e genera il relativo percorso `jsmith`. ONTAP ricerca ora una directory denominata `jsmith` selezionando ciascun percorso di ricerca nell'ordine indicato:

* `/vol0home/home/jsmith` non esiste; passaggio al percorso di ricerca n. 2.
* `/vol1home/home/jsmith` esiste; pertanto, il percorso di ricerca n. 3 non è selezionato; l'utente è ora connesso alla propria home directory.


Scenario 2: L'utente si connette a. `\\vs1\jsmith`. Corrisponde al secondo nome di condivisione della home directory e genera il relativo percorso `acme/jsmith`. ONTAP ricerca ora una directory denominata `acme/jsmith` selezionando ciascun percorso di ricerca nell'ordine indicato:

* `/vol0home/home/acme/jsmith` non esiste; passaggio al percorso di ricerca n. 2.
* `/vol1home/home/acme/jsmith` non esiste; si passa al percorso di ricerca #3.
* `/vol2home/home/acme/jsmith` non esiste; la home directory non esiste; pertanto, la connessione non riesce.




== Finestra Shares

È possibile utilizzare la finestra Shares (condivisioni) per gestire le condivisioni e visualizzare le informazioni sulle condivisioni.



=== Pulsanti di comando

* *Crea condivisione*
+
Apre la finestra di dialogo Create Share (Crea condivisione), che consente di creare una condivisione.

* *Crea home directory*
+
Apre la finestra di dialogo Crea condivisione home directory, che consente di creare una nuova condivisione home directory.

* *Modifica*
+
Apre la finestra di dialogo Modifica impostazioni, che consente di modificare le proprietà di una condivisione selezionata.

* *Interrompi condivisione*
+
Interrompe la condivisione dell'oggetto selezionato.

* *Aggiorna*
+
Aggiorna le informazioni nella finestra.





=== Shares

L'elenco Shares (condivisioni) visualizza il nome e il percorso di ciascuna condivisione.

* *Nome condivisione*
+
Visualizza il nome della condivisione.

* *Percorso*
+
Visualizza il nome completo del percorso di una cartella, qtree o volume esistente che è condiviso. I separatori di percorso possono essere barre rovesciate o barre in avanti, sebbene ONTAP visualizzi tutti i separatori di percorso come barre in avanti.

* *Home Directory*
+
Visualizza il nome della condivisione della home directory.

* *Commento*
+
Visualizza ulteriori descrizioni della condivisione, se presenti.

* *Condivisione a disponibilità continua*
+
Visualizza se la condivisione è abilitata per la disponibilità continua. A partire da System Manager 9.6, la disponibilità continua è supportata per i volumi FlexGroup.





=== Area dei dettagli

L'area sotto l'elenco delle condivisioni visualizza le proprietà di condivisione e i diritti di accesso per ciascuna condivisione.

* *Proprietà*
+
** Nome
+
Visualizza il nome della condivisione.

** Stato degli oplock
+
Specifica se la condivisione utilizza blocchi opportunistici (oplock).

** Esplorabile
+
Specifica se la condivisione può essere esplorata dai client Windows.

** Mostra snapshot
+
Specifica se le copie Snapshot possono essere visualizzate dai client.

** Share a disponibilità continua
+
Specifica se la condivisione è attivata o disattivata per la disponibilità continua. A partire da System Manager 9.6, la disponibilità continua è supportata per i volumi FlexGroup.

** Enumerazione basata sull'accesso
+
Specifica se l'enumerazione basata sull'accesso (ABE) è attivata o disattivata nella condivisione.

** BranchCache
+
Specifica se BranchCache è attivato o disattivato nella condivisione.

** Crittografia SMB
+
Specifica se la crittografia dei dati mediante SMB 3.0 è abilitata a livello di SVM (Storage Virtual Machine) o di share. Se la crittografia SMB è attivata a livello di SVM, la crittografia SMB viene applicata a tutte le condivisioni e il valore viene visualizzato come abilitato (a livello di SVM).

** Versioni precedenti
+
Specifica se le versioni precedenti possono essere visualizzate e ripristinate dal client.



* *Controllo dell'accesso alla condivisione*
+
Visualizza i diritti di accesso degli utenti di dominio, dei gruppi di dominio, degli utenti locali e dei gruppi locali per la condivisione.



*Informazioni correlate*

xref:task_setting_up_cifs.adoc[Configurazione di CIFS]
