---
permalink: online-help-96-97/reference_storage_tiers_window.html 
sidebar: sidebar 
keywords: online, help, storage, tier, window, command, button 
summary: 'È possibile utilizzare la finestra Storage Tier per visualizzare i dettagli dello spazio a livello di cluster e per aggiungere e visualizzare i dettagli dell"aggregato.' 
---
= Finestra livelli di storage in Gestore di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la finestra livelli di storage in Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e earier) per visualizzare i dettagli dello spazio a livello di cluster e aggiungere e visualizzare i dettagli dell'aggregato.

Il pannello Internal Tier (Tier interno) o il pannello Performance Tier (Tier prestazioni), se il cluster dispone di aggregati all flash (all SSD), visualizza i dettagli dello spazio a livello di cluster, come la somma delle dimensioni totali di tutti gli aggregati, lo spazio utilizzato dagli aggregati nel cluster, e lo spazio disponibile nel cluster.

Il pannello Cloud Tier visualizza i livelli cloud totali concessi in licenza nel cluster, lo spazio concesso in licenza utilizzato nel cluster e lo spazio concesso in licenza disponibile nel cluster. Il pannello Cloud Tier visualizza anche la capacità cloud senza licenza utilizzata.

Gli aggregati sono raggruppati per tipo e il pannello aggregato visualizza i dettagli relativi allo spazio aggregato totale, allo spazio utilizzato e allo spazio disponibile. Se i dati inattivi (cold) sono disponibili su un'unità a stato solido (SSD) o su un aggregato All Flash FAS, viene visualizzata anche la quantità di spazio utilizzata. È possibile selezionare l'aggregato ed eseguire qualsiasi azione correlata all'aggregato.



== Pulsanti di comando

* *Aggiungi aggregato*
+
Consente di creare un aggregato.

* *Azioni*
+
Fornisce le seguenti opzioni:

+
** *Cambia stato in*
+
Cambia lo stato dell'aggregato selezionato in uno dei seguenti stati:

+
*** *Online*
+
È consentito l'accesso in lettura e scrittura ai volumi contenuti in questo aggregato.

*** *Non in linea*
+
Non è consentito l'accesso in lettura e scrittura.

*** *Limita*
+
Alcune operazioni, come la ricostruzione della parità, sono consentite, ma non è consentito l'accesso ai dati.



** *Aggiungi capacità*
+
Consente di aggiungere capacità (HDD o SSD) agli aggregati esistenti.

** *Aggiungi cache*
+
Consente di aggiungere dischi cache (SSD) ad aggregati HDD o aggregati Flash Pool esistenti.

+
Non è possibile aggiungere dischi cache agli aggregati abilitati per FabricPool.

+
Questa opzione non è disponibile per un cluster contenente nodi con personalità ottimizzata per All Flash.

** *Mirror*
+
Consente di eseguire il mirroring degli aggregati.

** *Spostamento del volume*
+
Consente di spostare un volume FlexVol.







== Area dei dettagli

È possibile fare clic sul nome dell'aggregato per visualizzare informazioni dettagliate sull'aggregato.

* *Scheda Panoramica*
+
Visualizza informazioni dettagliate sull'aggregato selezionato e una rappresentazione grafica dell'allocazione dello spazio dell'aggregato, del risparmio di spazio dell'aggregato e delle performance dell'aggregato.

* *Scheda Disk Information (informazioni disco)*
+
Visualizza le informazioni sul layout del disco per l'aggregato selezionato.

* Scheda *Volumes*
+
Visualizza i dettagli relativi al numero totale di volumi sull'aggregato, allo spazio aggregato totale e allo spazio impegnato nell'aggregato.

* Scheda Performance (prestazioni)*
+
Visualizza i grafici che mostrano le metriche delle performance degli aggregati, inclusi throughput e IOPS. I dati delle metriche delle performance per i trasferimenti totali, in lettura e scrittura vengono visualizzati per throughput e IOPS, mentre i dati per SSD e HDD vengono registrati separatamente.

+
La modifica del fuso orario del client o del fuso orario del cluster influisce sui grafici delle metriche delle performance. Se si modifica il fuso orario del client o il fuso orario del cluster, aggiornare il browser per visualizzare i grafici aggiornati.



*Informazioni correlate*

xref:task_adding_cloud_tier.adoc[Aggiunta di un Tier cloud]

xref:task_attaching_aggregate_to_cloud_tier.adoc[Allegare un aggregato a un Tier cloud]

xref:task_deleting_cloud_tier.adoc[Eliminazione di un Tier cloud]

xref:task_editing_cloud_tier.adoc[Modifica di un Tier cloud]

xref:task_provisioning_storage_through_aggregates.adoc[Provisioning dello storage tramite aggregati]

xref:task_deleting_aggregates.adoc[Eliminazione di aggregati]

xref:task_editing_aggregates.adoc[Modifica degli aggregati]
