---
permalink: online-help-96-97/reference_protection_window.html 
sidebar: sidebar 
keywords: command, buttons, protection, window, relationship, vault, mirror, online, help, ls 
summary: 'È possibile utilizzare la finestra protezione per creare e gestire relazioni mirror, relazioni vault e relazioni mirror e vault e per visualizzare i dettagli di queste relazioni. La finestra di protezione non visualizza le relazioni di condivisione del carico (LS) e le relazioni di protezione dei dati di transizione (TDP).' 
---
= Finestra di protezione con Gestore di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la finestra di protezione con Gestore di sistema di ONTAP Classic (disponibile in ONTAP 9.7 e versioni precedenti) per creare e gestire relazioni di mirroring, relazioni di vault e relazioni di mirroring e vault e per visualizzare i dettagli di queste relazioni. La finestra di protezione non visualizza le relazioni di condivisione del carico (LS) e le relazioni di protezione dei dati di transizione (TDP).



== Pulsanti di comando

* *Crea*
+
Apre la finestra di dialogo Crea relazione di protezione, che consente di creare una relazione di mirroring, una relazione di vault o una relazione di mirroring e vault da un volume di destinazione.

+
System Manager non visualizza alcuna SVM (Storage Virtual Machine) configurata per il disaster recovery (DR) nella finestra di dialogo Crea relazione di protezione.

* *Modifica*
+
Apre la finestra di dialogo Modifica relazione di protezione, che consente di modificare la pianificazione e la policy di una relazione.

+
Per una relazione del vault, una relazione di mirror e vault o una relazione di mirror flessibile dalla versione, è possibile modificare il tipo di relazione modificando il tipo di policy.

* *Elimina*
+
Apre la finestra di dialogo Elimina relazione di protezione, che consente di eliminare una relazione.

* *Operazioni*
+
Visualizza le operazioni che possono essere eseguite su una relazione di protezione.

* *Aggiorna*
+
Aggiorna le informazioni nella finestra.





== Elenco delle relazioni di protezione

* *Source Storage Virtual Machine*
+
Visualizza la SVM che contiene il volume da cui i dati vengono mirrorati o archiviati in una relazione.

* *Volume di origine*
+
Visualizza il volume da cui i dati vengono mirrorati o archiviati in una relazione.

* *Volume di destinazione*
+
Visualizza il volume in cui i dati vengono mirrorati o archiviati in una relazione.

* *È in buona salute*
+
Visualizza se la relazione è sana o meno.

* *Tipo di oggetto*
+
Visualizza il tipo di oggetto della relazione, ad esempio Volume, FlexGroup o SVM.

* *Stato di relazione*
+
Visualizza lo stato della relazione, ad esempio SnapMirrored, Uninitialized o Broken Off.

* *Stato trasferimento*
+
Visualizza lo stato della relazione.

* *Tipo di relazione*
+
Visualizza il tipo di relazione, ad esempio mirror, vault o mirror e vault.

* *Tempo di ritardo*
+
Il tempo di ritardo è la differenza tra l'ora corrente e la data e l'ora dell'ultima copia Snapshot che è stata trasferita correttamente al sistema di destinazione. Il tempo di ritardo sarà sempre almeno pari alla durata dell'ultimo trasferimento riuscito, a meno che i clock sui sistemi di origine e di destinazione non siano sincronizzati. La differenza di fuso orario viene calcolata automaticamente nel tempo di ritardo.

* *Nome policy*
+
Visualizza il nome del criterio assegnato alla relazione.

* *Tipo di policy*
+
Visualizza il tipo di policy assegnato alla relazione. Il tipo di policy può essere StrictSync, Sync, Asynchronous Mirror, Asynchronous Vault o Asynchronous Mirror Vault.





== Area dei dettagli

* Scheda *Dettagli*
+
Visualizza informazioni generali sulla relazione selezionata, come il cluster di origine e il cluster di destinazione, la velocità di trasferimento dei dati, lo stato della relazione, i dettagli sul rapporto di compressione di rete, lo stato del trasferimento dei dati, il tipo di trasferimento dei dati corrente, il tipo di ultimo trasferimento dei dati, l'ultima copia Snapshot, E data e ora dell'ultima copia Snapshot.

* *Scheda Policy Details (Dettagli policy)*
+
Visualizza i dettagli relativi al criterio assegnato alla relazione di protezione selezionata. Questa scheda visualizza anche l'etichetta SnapMirror e i programmi di copia Snapshot nel volume di origine che corrispondono all'etichetta specificata.

* *Scheda Snapshot Copies*
+
Visualizza il numero di copie Snapshot con l'attributo di etichetta SnapMirror per la relazione di protezione selezionata e l'indicazione dell'ora dell'ultima copia Snapshot.


