---
permalink: online-help-96-97/task_provisioning_basic_template.html 
sidebar: sidebar 
keywords: sap, hana, provisioning, basic, template, online, help, system, manager 
summary: È possibile utilizzare System Manager per eseguire rapidamente il provisioning di modelli di base per SAP HANA. 
---
= Eseguire il provisioning di un modello di base con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per eseguire rapidamente il provisioning dei modelli di base per SAP HANA.

.A proposito di questa attività
In qualità di amministratore del cluster, è possibile eseguire il provisioning delle applicazioni configurando un modello di base. Nell'esempio viene descritto come configurare *SAP HANA Server*.

.Fasi
. Fare clic su *applicazioni e livelli* > *applicazioni*
. Nella scheda *Basic*, selezionare il modello *SAP HANA Server*.
. Nella sezione **Dettagli database**, specificare quanto segue:
+
** Nome del database
** Dimensione del database
** Dimensione del log
** Dimensione del tempdb
** Numero di core del server
** Note sul controller ha di span


. Fare clic su *Provision Storage* (Provision Storage


.Risultati
Viene eseguito il provisioning dell'applicazione SAP HANA Server.

*Informazioni correlate*

link:reference_application_provisioning_settings.html["Per le descrizioni dei campi, fare riferimento a Impostazioni di provisioning dell'applicazione"]
