---
permalink: online-help-96-97/task_monitoring_ha_pairs.html 
sidebar: sidebar 
keywords: system, manager, ha, availability, monitor, ha, pair 
summary: 'È possibile utilizzare System Manager per monitorare lo stato del nodo e dello stato di interconnessione di tutte le coppie ad alta disponibilità (ha) in un cluster. È inoltre possibile verificare se è stata attivata o meno la funzione di Takeover o giveback e visualizzare i motivi per cui al momento non è possibile effettuare il takeover o il giveback.' 
---
= Monitorare le coppie ha con System Manager - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per monitorare lo stato del nodo e dello stato di interconnessione di tutte le coppie ad alta disponibilità (ha) in un cluster. È inoltre possibile verificare se è stata attivata o meno la funzione di Takeover o giveback e visualizzare i motivi per cui al momento non è possibile effettuare il takeover o il giveback.

.Fasi
. Fare clic su *Configuration* > *Cluster* > *High Availability*.
. Nella finestra *High Availability*, fare clic sull'immagine ha Pair per visualizzare dettagli quali lo stato ha del cluster, lo stato del nodo, lo stato di interconnessione e il modello hardware di ciascun nodo.
+
Se la LIF di gestione del cluster o le LIF di dati di un nodo non si trovano nel nodo principale, viene visualizzato un messaggio di avviso che indica che il nodo ha alcune LIF che non si trovano nel nodo principale.



*Informazioni correlate*

xref:reference_high_availability.adoc[Finestra High Availability]
