---
permalink: online-help-96-97/task_aborting_vault_relationships.html 
sidebar: sidebar 
keywords: abort, snapshot, copy, transfer, online, help, system, manager 
summary: È possibile utilizzare System Manager per interrompere o interrompere un trasferimento di dati in corso. 
---
= Interrompere un trasferimento di copia Snapshot con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per interrompere o interrompere un trasferimento di dati in corso.

.Fasi
. Fare clic su *Protection* > *Volume Relares* (protezione* > *Relazioni volume*
. Selezionare la relazione per la quale si desidera interrompere il trasferimento dei dati e fare clic su *operazioni* > *Interrompi*.
. Selezionare la casella di controllo *Sì, desidero interrompere il trasferimento* per confermare l'operazione.
. *Opzionale:* selezionare la casella di controllo *Mantieni tutti i dati parzialmente trasferiti* per conservare i dati già trasferiti nel volume di destinazione.
. Fare clic su *Interrompi*.


.Risultati
Lo stato del trasferimento viene visualizzato come "`in corso`" fino al completamento dell'operazione e visualizzato come "`inattivo`" al termine dell'operazione.

*Informazioni correlate*

xref:reference_protection_window.adoc[Finestra di protezione]
