---
permalink: online-help-96-97/task_editing_application.html 
sidebar: sidebar 
keywords: edit, application, online, help, provisioned, snapshot, copy 
summary: 'È possibile modificare un"applicazione con provisioning per aumentare le dimensioni dello storage o gestire le copie Snapshot dell"applicazione.' 
---
= Modificare un'applicazione con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per modificare un'applicazione con provisioning per aumentare le dimensioni dello storage o gestire le copie Snapshot dell'applicazione.

.A proposito di questa attività
In qualità di amministratore del cluster, dopo aver eseguito il provisioning di un'applicazione, è possibile modificarla per modificare le dimensioni dello storage. È inoltre possibile creare, ripristinare o eliminare le copie Snapshot dell'applicazione. La procedura di esempio che segue descrive come modificare un'applicazione *NAS container*.

.Fasi
. Fare clic su *applicazioni e livelli* > *applicazioni*
. Fare clic sul nome dell'applicazione container NAS.
+
[NOTE]
====
Se qualcuno aggiunge nuove applicazioni utilizzando l'API CLI o REST mentre si visualizza l'elenco di applicazioni, non sarà possibile visualizzarle quando si scorre l'elenco.

====
+
La scheda *Panoramica* della finestra Dettagli applicazione: nas visualizza le impostazioni dell'applicazione.

. Fare clic su *Edit* (Modifica).
+
La finestra Edit NAS container: nas (Modifica contenitore NAS: nas) visualizza l'impostazione della dimensione dello storage corrente e l'indirizzo *NFS Access - Grant Access to host* (accesso NFS - Consenti accesso all'host).

. Modificare il valore *Storage Total Size*.
. Nel campo size units (unità di misura), selezionare dal menu a discesa per specificare le unità di misura corrette (byte, MB, GB o TB).
. Nel campo *livello di servizio ONTAP*, selezionare dal menu a discesa per specificare il valore.
. Fare clic su *Save* (Salva).
. Tornare alla finestra *Application Details: nas* e selezionare la scheda **Snapshot Copies**.
+
Viene visualizzato un elenco di copie Snapshot per questa applicazione con provisioning. È possibile utilizzare il campo *Cerca* per cercare le copie Snapshot in base al nome.

. Gestire le copie Snapshot eseguendo le seguenti operazioni, se necessario:
+
|===
| Attività | Azioni 


 a| 
Creare
 a| 
Fare clic su *Create* (Crea) per creare una nuova copia Snapshot.



 a| 
Ripristinare
 a| 
Fare clic sulle caselle di controllo accanto alle copie Snapshot che si desidera ripristinare, quindi fare clic su *Restore* (Ripristina).



 a| 
Eliminare
 a| 
Fare clic sulle caselle di controllo accanto alle copie Snapshot che si desidera eliminare, quindi fare clic su *Delete* (Elimina).

|===

