---
permalink: online-help-96-97/task_changing_status_flexgroup_volume.html 
sidebar: sidebar 
keywords: flexgroup, volume, status, change, online, help 
summary: 'È possibile utilizzare Gestione sistema per modificare lo stato di un volume FlexGroup quando si desidera disattivare un volume FlexGroup, ripristinare un volume FlexGroup online o limitare l"accesso a un volume FlexGroup.' 
---
= Modificare lo stato di un volume FlexGroup con Gestione sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per modificare lo stato di un volume FlexGroup quando si desidera disattivare un volume FlexGroup, ripristinare un volume FlexGroup online o limitare l'accesso a un volume FlexGroup.

.A proposito di questa attività
System Manager non supporta la gestione a livello di componente per i volumi FlexGroup.

.Fasi
. Fare clic su *Storage* > *Volumes*.
. Dal menu a discesa nel campo *SVM*, selezionare *All SVM*.
. Selezionare il volume FlexGroup per il quale si desidera modificare lo stato.
. Fare clic su *altre azioni* > *Cambia stato in*, quindi aggiornare lo stato del volume FlexGroup selezionando lo stato desiderato.


*Informazioni correlate*

xref:reference_volumes_window.adoc[Finestra Volumes (volumi]
