---
permalink: online-help-96-97/task_hiding_snapshot_copy_directory.html 
sidebar: sidebar 
keywords: hide, snapshot, copy, directory, system, manager, online, help 
summary: 'È possibile utilizzare System Manager per nascondere la directory di copia Snapshot (.snapshot) in modo che la directory di copia Snapshot non sia visibile quando si visualizzano le directory dei volumi. Per impostazione predefinita, la directory .snapshot è visibile.' 
---
= Nascondere la directory di copia Snapshot con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestione di sistema ONTAP classico (disponibile in ONTAP 9,7 e versioni precedenti) per nascondere la directory di copia istantanea  `.snapshot`) In modo che la directory di copia Snapshot non sia visibile quando si visualizzano le directory dei volumi. Per impostazione predefinita, il `.snapshot` la directory è visibile.

.Fasi
. Fare clic su *Storage* > *Volumes*.
. Dal menu a discesa nel campo *SVM*, selezionare *All SVM*.
. Selezionare il volume per il quale si desidera nascondere la directory di copia Snapshot.
. Fare clic su *altre azioni* > *Gestisci snapshot* > *Impostazioni di configurazione*.
. Assicurarsi che l'opzione *Make snapshot directory (.snapshot) visible* non sia selezionata, quindi fare clic su *OK*.


*Informazioni correlate*

xref:reference_volumes_window.adoc[Finestra Volumes (volumi]
