---
permalink: online-help-96-97/task_editing_initiator_groups.html 
sidebar: sidebar 
keywords: edit, initiator, group, system, manager, online, help, port, set, dialog, box 
summary: 'È possibile utilizzare la finestra di dialogo Edit Initiator Group (Modifica gruppo iniziatore) in System Manager per modificare il nome di un gruppo iniziatore esistente e del relativo sistema operativo. È possibile aggiungere o rimuovere gli iniziatori dal gruppo di iniziatori. È inoltre possibile modificare il set di porte associato al gruppo iniziatore.' 
---
= Modificare i gruppi di iniziatori con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la finestra di dialogo *Modifica gruppo iniziatore* in Gestore di sistema di ONTAP Classic (disponibile in ONTAP 9.7 e versioni precedenti) per modificare il nome di un gruppo iniziatore esistente e del relativo sistema operativo. È possibile aggiungere o rimuovere gli iniziatori dal gruppo di iniziatori. È inoltre possibile modificare il set di porte associato al gruppo iniziatore.

.Fasi
. Fare clic su *Storage* > *LUN*.
. Nella scheda *Initiator Groups*, selezionare il gruppo di iniziatori che si desidera modificare, quindi fare clic su *Edit* (Modifica).
. Apportare le modifiche necessarie.
. Fare clic su *Save and Close* (Salva e chiudi).
. Verificare le modifiche apportate al gruppo iniziatore nella scheda *Initiator Groups*.


*Informazioni correlate*

xref:reference_luns_window.adoc[Finestra LUN]
