---
permalink: online-help-96-97/task_editing_initiators.html 
sidebar: sidebar 
keywords: edit, initiator, online, help, group, dialog, system, manager 
summary: 'È possibile utilizzare la finestra di dialogo Edit Initiator Group (Modifica gruppo iniziatore) in System Manager per modificare il nome di un iniziatore esistente in un gruppo iniziatore.' 
---
= Modifica degli iniziatori con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la finestra di dialogo *Modifica gruppo iniziatore* in Gestore di sistema ONTAP Classic (disponibile in ONTAP 9.7 e versioni precedenti) per modificare il nome di un iniziatore esistente in un gruppo iniziatore.

.Fasi
. Fare clic su *Storage* > *LUN*.
. Nella scheda *Initiator Groups*, selezionare il gruppo di iniziatori a cui appartiene l'iniziatore, quindi fare clic su *Edit* (Modifica).
. Nella finestra di dialogo *Edit Initiator Group* (Modifica gruppo iniziatore), fare clic su *Initiator* (iniziatori).
. Selezionare l'iniziatore che si desidera modificare e fare clic su *Edit* (Modifica).
. Modificare il nome e fare clic su *OK*.
. Fare clic su *Save and Close* (Salva e chiudi).


*Informazioni correlate*

xref:reference_luns_window.adoc[Finestra LUN]
