---
permalink: online-help-96-97/task_aborting_mirror_vault_relationships.html 
sidebar: sidebar 
keywords: abort, mirror, vault, relationship, online, help, data, transfer 
summary: 'È possibile interrompere un"operazione di replica del volume se si desidera interrompere il trasferimento dei dati. È possibile interrompere un aggiornamento pianificato, un aggiornamento manuale o un trasferimento iniziale dei dati.' 
---
= Interrompere le relazioni di mirror e vault con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera interrompere il trasferimento dei dati, è possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per interrompere un'operazione di replica del volume. È possibile interrompere un aggiornamento pianificato, un aggiornamento manuale o un trasferimento iniziale dei dati.

.Fasi
. Fare clic su *Protection* > *Volume Relares* (protezione* > *Relazioni volume*
. Selezionare la relazione del mirror e del vault per cui si desidera interrompere il trasferimento dei dati, quindi fare clic su *operazioni* > *Interrompi*.
. Selezionare la casella di controllo *Sì, desidero interrompere il trasferimento* per confermare l'operazione.
. *Opzionale:* selezionare la casella di controllo *Mantieni tutti i dati parzialmente trasferiti* per conservare i dati già trasferiti nel volume di destinazione.
. Fare clic su *Interrompi*.


.Risultati
Lo stato del trasferimento viene visualizzato come "`in corso`" fino al completamento dell'operazione e visualizzato come "`inattivo`" al termine dell'operazione.
