---
permalink: online-help-96-97/task_resetting_cifs_domain_controllers.html 
sidebar: sidebar 
keywords: reset, cifs, domain, controller, system, manager, online, help 
summary: È possibile utilizzare System Manager per ripristinare la connessione CIFS ai controller di dominio per il dominio specificato. Il mancato ripristino delle informazioni del controller di dominio può causare un errore di connessione. 
---
= Ripristinare i controller di dominio CIFS con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per ripristinare la connessione CIFS ai controller di dominio per il dominio specificato. Il mancato ripristino delle informazioni del controller di dominio può causare un errore di connessione.

.A proposito di questa attività
È necessario aggiornare le informazioni di rilevamento del controller di dominio disponibile del sistema di storage dopo aver aggiunto o eliminato un dominio dall'elenco dei controller di dominio preferiti. È possibile aggiornare le informazioni di rilevamento dei controller di dominio disponibili nel sistema di storage in ONTAP tramite l'interfaccia della riga di comando (CLI).

.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM, quindi fare clic su *SVM Settings* (Impostazioni SVM).
. Nella scheda *dominio*, fare clic su *Ripristina*.


*Informazioni correlate*

xref:reference_cifs_window.adoc[Finestra CIFS]
