---
permalink: online-help-96-97/task_editing_vault_relationships.html 
sidebar: sidebar 
keywords: edit, vault, relationships, system, manager, online, help, cluster, schedule 
summary: È possibile utilizzare System Manager per modificare una relazione di vault selezionando una policy o una pianificazione esistente nel cluster o creando una nuova policy o pianificazione. Tuttavia, non è possibile modificare i parametri di una policy o di una pianificazione esistente. 
---
= Gestire le relazioni dei vault con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per aggiornare, riprendere, interrompere, inizializzare ed eliminare le relazioni dei vault, oltre a creare relazioni dei vault da una SVM di destinazione.



== Modificare le relazioni

È possibile utilizzare System Manager per modificare una relazione di vault selezionando una policy o una pianificazione esistente nel cluster o creando una nuova policy o pianificazione. Tuttavia, non è possibile modificare i parametri di una policy o di una pianificazione esistente.

.Prima di iniziare
I cluster di origine e di destinazione devono essere in una relazione paritarie sana.

.Fasi
. Fare clic su *Protection* > *Volume Relares* (protezione* > *Relazioni volume*
. Selezionare la relazione del vault per cui si desidera modificare la policy o la pianificazione, quindi fare clic su *Modifica*.
. Nella finestra di dialogo *Modifica relazione*, selezionare l'azione appropriata:
+
|===
| Se si desidera... | Effettuare le seguenti operazioni... 


 a| 
Selezionare un criterio esistente
 a| 
Fare clic su *Sfoglia*, quindi selezionare un criterio esistente.    È possibile selezionare un criterio con il numero massimo di etichette corrispondenti con il criterio Snapshot collegato al volume di origine.



 a| 
Creare una nuova policy
 a| 
.. Fare clic su *Crea policy*.
.. Specificare un nome per il criterio.
.. Impostare la priorità per i trasferimenti pianificati.
+
Low (basso) indica che il trasferimento ha la priorità minore e viene di solito pianificato dopo i trasferimenti con priorità normale. Per impostazione predefinita, la priorità è impostata su normale.

.. Selezionare la casella di controllo *Enable Network Compression* (Abilita compressione di rete) per comprimere i dati trasferiti.
.. Specificare un'etichetta SnapMirror e il numero di conservazione della destinazione per la policy del vault.
+
Per rendere effettiva la nuova etichetta SnapMirror, è necessario assicurarsi che sul volume di origine venga creata una copia Snapshot con la stessa etichetta.

.. Fare clic su *Create* (Crea).


|===
. Specificare una pianificazione per la relazione:
+
|===
| Se... | Effettuare le seguenti operazioni... 


 a| 
Si desidera assegnare una pianificazione esistente
 a| 
Selezionare una pianificazione esistente dall'elenco.



 a| 
Si desidera creare una nuova pianificazione
 a| 
.. Fare clic su *Crea pianificazione*.
.. Specificare un nome per la pianificazione.
.. Selezionare una delle seguenti opzioni:
+
*** *Di base*
+
È possibile selezionare questa opzione per specificare solo il giorno della settimana, l'ora e l'intervallo di trasferimento.

*** *Avanzate*
+
È possibile selezionare questa opzione per specificare una pianificazione in stile cron.



.. Fare clic su *Create* (Crea).




 a| 
Non si desidera assegnare una pianificazione
 a| 
Selezionare *Nessuno*.

|===
. Fare clic su *OK*.


*Informazioni correlate*

xref:reference_protection_window.adoc[Finestra di protezione]



== Inizializzare le relazioni

È possibile utilizzare System Manager per inizializzare una relazione del vault se non è già stata inizializzata durante la creazione della relazione. Viene avviato un trasferimento baseline dei dati dal volume FlexVol di origine al volume FlexVol di destinazione.

.Prima di iniziare
I cluster di origine e di destinazione devono essere in una relazione paritarie sana.

.Fasi
. Fare clic su *Protection* > *Volume Relares* (protezione* > *Relazioni volume*
. Selezionare la relazione che si desidera inizializzare e fare clic su *operazioni* > *Inizializza*.
. Nella finestra *Inizializza*, fare clic su *Inizializza*.


.Risultati
Una copia Snapshot viene creata e trasferita alla destinazione.

Questa copia Snapshot viene utilizzata come riferimento per le successive copie Snapshot incrementali.

*Informazioni correlate*

xref:reference_protection_window.adoc[Finestra di protezione]



== Creare relazioni da una SVM di destinazione

È possibile utilizzare System Manager per creare una relazione di vault dalla macchina virtuale di storage di destinazione (SVM) e assegnare una policy di vault per creare un vault di backup. In caso di perdita o danneggiamento dei dati su un sistema, è possibile ripristinare i dati di backup dalla destinazione del vault di backup.

.Prima di iniziare
* Il cluster di origine deve eseguire ONTAP 8.2.2 o versione successiva.
* La licenza SnapVault o la licenza SnapMirror devono essere attivate sia sul cluster di origine che sul cluster di destinazione.
+
[NOTE]
====
Per alcune piattaforme, non è obbligatorio che la licenza SnapVault o la licenza SnapMirror del cluster di origine siano attivate se il cluster di destinazione dispone della licenza SnapVault o SnapMirror e della licenza DPO attivate.

====
* Il cluster di origine e il cluster di destinazione devono essere in una relazione di pari livello.
* La SVM di destinazione deve disporre di spazio disponibile.
* L'aggregato di origine e l'aggregato di destinazione devono essere aggregati a 64 bit.
* Deve esistere un volume di origine di tipo Read/Write (rw).
* Deve esistere una policy di vault (XDP).
+
Se non esiste una policy del vault, è necessario creare una policy del vault o accettare la policy del vault predefinita (XDPDefault) assegnata automaticamente.

* I volumi FlexVol devono essere online e di lettura/scrittura.
* Il tipo di aggregato SnapLock deve essere lo stesso.
* Se si effettua la connessione da un cluster che esegue ONTAP 9.2 o versioni precedenti a un cluster remoto su cui è attivata l'autenticazione SAML, è necessario attivare l'autenticazione basata su password nel cluster remoto.


.A proposito di questa attività
* System Manager non supporta una relazione a cascata.
+
Ad esempio, un volume di destinazione in una relazione non può essere il volume di origine in un'altra relazione.

* Non è possibile creare una relazione di vault tra una SVM di origine della sincronizzazione e una SVM di destinazione della sincronizzazione in una configurazione MetroCluster.
* È possibile creare una relazione di vault tra le SVM di origine della sincronizzazione in una configurazione MetroCluster.
* È possibile creare una relazione di vault da un volume su una SVM di origine della sincronizzazione a un volume su una SVM di servizio dati.
* È possibile creare una relazione di vault da un volume su una SVM di servizio dati a un volume di protezione dati (DP) su una SVM di origine sincronizzazione.
* È possibile creare una relazione di vault solo tra un volume non SnapLock (primario) e un volume di destinazione SnapLock (secondario).
* È possibile proteggere un massimo di 25 volumi in un'unica selezione.


.Fasi
. Fare clic su *Protection* > *Volume Relares* (protezione* > *Relazioni volume*
. Nella finestra *Relazioni*, fare clic su *Crea*.
. Nella finestra di dialogo *Browse SVM* (Sfoglia SVM), selezionare un SVM per il volume di destinazione.
. Nella finestra di dialogo *Crea relazione di protezione*, selezionare *Vault* dall'elenco a discesa *tipo di relazione*.
. Specificare il cluster, la SVM e il volume di origine.
+
Se il cluster specificato esegue una versione del software ONTAP precedente a ONTAP 9.3, vengono elencate solo le SVM in peering. Se il cluster specificato esegue ONTAP 9.3 o versione successiva, vengono elencate le SVM in peering e le SVM consentite.

. Inserire un suffisso del nome del volume.
+
Il suffisso del nome del volume viene aggiunto ai nomi del volume di origine per generare i nomi del volume di destinazione.

. Se si crea un volume SnapLock, specificare il periodo di conservazione predefinito.
+
Il periodo di conservazione predefinito può essere impostato su qualsiasi valore compreso tra 1 giorno e 70 anni o Infinito.

. *Opzionale:* fare clic su *Sfoglia*, quindi modificare la policy del vault.
. Selezionare una pianificazione per la relazione dall'elenco delle pianificazioni esistenti.
. *Opzionale:* selezionare *Inizializza relazione* per inizializzare la relazione del vault.
. Abilitare SnapLock gli aggregati aziendali, quindi selezionare un aggregato di conformità SnapLock o un aggregato aziendale SnapLock.
. Abilitare gli aggregati abilitati a FabricPool, quindi selezionare un criterio di tiering appropriato.
. Fare clic su *Validate* (convalida) per verificare se i volumi selezionati hanno etichette corrispondenti.
. Fare clic su *Create* (Crea).


.Risultati
Se si sceglie di creare un volume di destinazione, viene creato un volume di tipo _dp_ con le seguenti impostazioni predefinite:

* La funzione di crescita automatica è attivata.
* La deduplica viene attivata o disattivata in base alle preferenze dell'utente o all'impostazione della deduplica del volume di origine.
* La compressione è disattivata.
* L'attributo language viene impostato in modo che corrisponda all'attributo language del volume di origine.


Viene creata una relazione di vault tra il volume di destinazione e il volume di origine. La copia Snapshot di base viene trasferita al volume di destinazione se si è scelto di inizializzare la relazione.



== Aggiornare le relazioni

È possibile utilizzare System Manager per avviare manualmente un aggiornamento incrementale non pianificato. Potrebbe essere necessario un aggiornamento manuale per evitare la perdita di dati dovuta a un'imminente interruzione dell'alimentazione, manutenzione pianificata o migrazione dei dati.

.Prima di iniziare
La relazione del vault deve essere inizializzata.

.Fasi
. Fare clic su *Protection* > *Volume Relares* (protezione* > *Relazioni volume*
. Selezionare la relazione per la quale si desidera aggiornare i dati e fare clic su *Operations* > *Update* (operazioni).
. Scegliere una delle seguenti opzioni:
+
** Selezionare *come da policy* per eseguire un trasferimento incrementale dalla copia Snapshot comune recente tra i volumi di origine e di destinazione.
** Selezionare *Select Snapshot copy* (Seleziona copia istantanea) e specificare la copia Snapshot che si desidera trasferire.


. *Opzionale:* selezionare *limita larghezza di banda di trasferimento a* per limitare la larghezza di banda di rete utilizzata per i trasferimenti e specificare la velocità massima di trasferimento.
. Fare clic su *Aggiorna*.
. Verificare lo stato del trasferimento nella scheda *Dettagli*.




== Eliminare le relazioni

È possibile utilizzare System Manager per terminare una relazione di vault tra un volume di origine e di destinazione e rilasciare le copie Snapshot dall'origine.

.A proposito di questa attività
Il rilascio della relazione rimuove in modo permanente le copie Snapshot di base utilizzate dalla relazione del vault sul volume di origine. Per ricreare la relazione del vault, è necessario eseguire l'operazione di risincronizzazione dal volume di origine utilizzando l'interfaccia della riga di comando (CLI).

.Fasi
. Fare clic su *Protection* > *Volume Relares* (protezione* > *Relazioni volume*
. Selezionare il volume per il quale si desidera eliminare la relazione del vault e fare clic su *Delete* (Elimina).
. Selezionare la casella di controllo di conferma, quindi fare clic su *Elimina*.
+
È inoltre possibile selezionare la casella di controllo copie Snapshot della release base per eliminare le copie Snapshot di base utilizzate dalla relazione del vault sul volume di origine.

+
Se la relazione non viene rilasciata, è necessario utilizzare la CLI per eseguire l'operazione di release sul cluster di origine per eliminare le copie Snapshot di base create per la relazione del vault dal volume di origine.





== Riprendere le relazioni

È possibile riprendere una relazione di vault in modalità di disattivazione utilizzando System Manager. Quando si riprende la relazione, viene ripristinato il normale trasferimento dei dati al volume FlexVol di destinazione e tutte le attività del vault vengono riavviate.

.Fasi
. Fare clic su *Protection* > *Volume Relares* (protezione* > *Relazioni volume*
. Selezionare la relazione per la quale si desidera riprendere il trasferimento dei dati e fare clic su *operazioni* > *Riprendi*.
. Nella finestra *Riprendi*, fare clic su *Riprendi*.


.Risultati
Vengono ripristinati i normali trasferimenti di dati. Se è presente un trasferimento pianificato per la relazione, il trasferimento viene avviato dalla pianificazione successiva.



== Interrompere le relazioni

È possibile utilizzare Gestione sistema per disattivare i trasferimenti di dati al volume FlexVol di destinazione rinunciando alla relazione del vault.

.Fasi
. Fare clic su *Protection* > *Volume Relares* (protezione* > *Relazioni volume*
. Selezionare la relazione per la quale si desidera interrompere i trasferimenti di dati pianificati e fare clic su *operazioni* > *Quiesce*.
. Nella finestra *Quiesce*, fare clic su *Quiesce*.


.Risultati
Se non è in corso alcun trasferimento, lo stato del trasferimento viene visualizzato come Quiesced. Se è in corso un trasferimento, il trasferimento non viene compromesso e lo stato del trasferimento viene visualizzato come Quiescing (in attesa) fino al completamento del trasferimento.

*Informazioni correlate*

xref:reference_protection_window.adoc[Finestra di protezione]
