---
permalink: online-help-96-97/task_reassigning_disks_to_nodes.html 
sidebar: sidebar 
keywords: system, manager, reassign, disks, node, online, help, node, aggregate, storage, pool 
summary: È possibile utilizzare System Manager per riassegnare la proprietà dei dischi spare da un nodo a un altro per aumentare la capacità di un aggregato o di un pool di storage. 
---
= Riassegnare i dischi ai nodi con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per riassegnare la proprietà dei dischi spare da un nodo a un altro per aumentare la capacità di un aggregato o di un pool di storage.

.A proposito di questa attività
* È possibile riassegnare i dischi se sono soddisfatte le seguenti condizioni:
+
** Il tipo di contenitore dei dischi selezionati deve essere "`spare`" o "`shared`".
** I dischi devono essere collegati ai nodi in una configurazione ad alta disponibilità.
** I dischi devono essere visibili al nodo.


* Non è possibile riassegnare un disco se sono soddisfatte le seguenti condizioni:
+
** Il tipo di contenitore del disco selezionato è "`shared`" e la partizione dei dati non è spare.
** Il disco è associato a un pool di storage.


* Non è possibile riassegnare la partizione dei dati dei dischi condivisi se il failover dello storage non è attivato sui nodi associati ai dischi condivisi.
* Per i dischi di partizione, è possibile riassegnare solo la partizione dei dati dei dischi.
* Per le configurazioni MetroCluster, non è possibile utilizzare Gestione di sistema per riassegnare i dischi.
+
È necessario utilizzare l'interfaccia della riga di comando per riassegnare i dischi per le configurazioni MetroCluster.



[NOTE]
====
Nelle versioni successive di ONTAP, si utilizza la CLI di ONTAP per rimuovere la proprietà del disco e quindi assegnare un nuovo proprietario.

====
.Fasi
. Fare clic su *Storage* > *Aggregates & Disks* > *Disks*.
. Nella finestra *dischi*, selezionare la scheda *inventario*.
. Selezionare i dischi che si desidera riassegnare, quindi fare clic su *Assegna*.
. Nella finestra di dialogo *Avviso*, fare clic su *continua*.
. Nella finestra di dialogo *Assegna dischi*, selezionare il nodo a cui si desidera riassegnare i dischi.
. Fare clic su *Assegna*.


.Informazioni correlate
* link:https://docs.netapp.com/us-en/ontap/disks-aggregates/remove-ownership-disk-task.html["Rimozione della proprietà dei dischi mediante la CLI di ONTAP (ONTAP 9,3 e versioni successive)"]
* link:https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html["Assegnazione automatica dei dischi utilizzando la CLI di ONTAP (ONTAP 9,3 e versioni successive)"]
* link:https://docs.netapp.com/us-en/ontap/disks-aggregates/manual-assign-disks-ownership-manage-task.html["Assegnazione manuale dei dischi mediante l'interfaccia CLI di ONTAP (ONTAP 9,3 e versioni successive)"]

