---
permalink: online-help-96-97/task_stopping_svms.html 
sidebar: sidebar 
keywords: stop, svm, online, help, system, manager, storage, virtual, machine 
summary: 'È possibile utilizzare System Manager per arrestare una macchina virtuale di storage (SVM) se si desidera risolvere qualsiasi problema relativo a SVM, eliminare SVM o interrompere l"accesso ai dati da SVM.' 
---
= Arrestare le SVM con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per arrestare una macchina virtuale di storage (SVM) se si desidera risolvere qualsiasi problema relativo a SVM, eliminare SVM o interrompere l'accesso ai dati da SVM.

.Prima di iniziare
Tutti i client connessi alla SVM devono essere disconnessi.

[NOTE]
====
Se alcuni client sono connessi a SVM quando viene interrotto, potrebbe verificarsi una perdita di dati.

====
.A proposito di questa attività
* Non è possibile arrestare le SVM durante il failover dello storage (SFO).
* Quando si arresta la SVM, un amministratore della SVM non può accedere alla SVM.


.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM che si desidera arrestare, quindi fare clic su *Stop*.


.Risultati
SVM interrompe la fornitura dei dati ai client.
