---
permalink: online-help-96-97/task_deleting_flexgroup_volumes.html 
sidebar: sidebar 
keywords: delete, flexgroup, volumes, online, help, system, manager 
summary: È possibile utilizzare Gestione sistema per eliminare un volume FlexGroup quando non è più necessario il volume FlexGroup. 
---
= Eliminazione dei volumi FlexGroup con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Gestore di sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti) per eliminare un volume FlexGroup quando non è più necessario il volume FlexGroup.

.Prima di iniziare
* Il percorso di giunzione del volume FlexGroup deve essere smontato.
* Il volume FlexGroup deve essere offline.


.A proposito di questa attività
System Manager non supporta il livello di gestione dei componenti per i volumi FlexGroup.

.Fasi
. Fare clic su *Storage* > *Volumes*.
. Dal menu a discesa nel campo *SVM*, selezionare *All SVM*.
. Selezionare il volume FlexGroup che si desidera eliminare, quindi fare clic su *Elimina*.
. Selezionare la casella di controllo di conferma, quindi fare clic su *OK*.


*Informazioni correlate*

xref:reference_volumes_window.adoc[Finestra Volumes (volumi]
