---
permalink: online-help-96-97/task_updating_cifs_group_policy_configuration.html 
sidebar: sidebar 
keywords: update, cifs, group, policy, configuration, online, help, enable, disable, modify, reload, set, up 
summary: 'È necessario aggiornare i criteri di gruppo dopo aver modificato la configurazione dei criteri tramite l"interfaccia della riga di comando (CLI). È possibile utilizzare la finestra CIFS in System Manager per aggiornare i criteri di gruppo.' 
---
= Gestire la configurazione dei criteri di gruppo CIFS con Gestione di sistema - ONTAP 9.7 e versioni precedenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per aggiornare e gestire i criteri di gruppo, è possibile utilizzare la finestra CIFS in Gestione sistema ONTAP classic (disponibile in ONTAP 9.7 e versioni precedenti).



== Aggiornare la configurazione dei criteri di gruppo CIFS

È necessario aggiornare i criteri di gruppo dopo aver modificato la configurazione dei criteri tramite l'interfaccia della riga di comando (CLI).

.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM, quindi fare clic su *SVM Settings* (Impostazioni SVM).
. Fare clic sulla scheda *dominio*.
. Nell'area *Criteri di gruppo*, selezionare la configurazione dei criteri di gruppo che si desidera aggiornare, quindi fare clic su *Aggiorna*.




== Attivare o disattivare una configurazione dei criteri di gruppo CIFS

È possibile attivare o disattivare la configurazione dei criteri di gruppo CIFS dalla finestra CIFS in System Manager.

.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM, quindi fare clic su *SVM Settings* (Impostazioni SVM).
. Fare clic sulla scheda *dominio*.
. Nell'area *Criteri di gruppo*, selezionare la configurazione dei criteri di gruppo che si desidera attivare o disattivare, quindi fare clic su *attiva* o *Disattiva*, a seconda delle esigenze.




== Ricaricare la policy di gruppo CIFS

Se lo stato del criterio viene modificato, è necessario ricaricare un criterio di gruppo CIFS. È possibile utilizzare la finestra CIFS in System Manager per ricaricare i criteri di gruppo.

.Fasi
. Fare clic su *Storage* > *SVM*.
. Selezionare la SVM, quindi fare clic su *SVM Settings* (Impostazioni SVM).
. Fare clic sulla scheda *dominio*.
. Nell'area *Criteri di gruppo*, selezionare la configurazione dei criteri di gruppo che si desidera ricaricare, quindi fare clic su *ricarica*.

