---
permalink: nfs-config-esxi/task_adding_storage_cluster_to_virtual_storage_cluster.html 
sidebar: sidebar 
keywords: provision, datastore, esxi, host, datacenter, cluster, add, enable, storage, add, add the storage cluster or to vsc for 
summary: 'Prima di eseguire il provisioning del primo datastore a un host ESXi nel data center, è necessario aggiungere il cluster o uno specifico a per . L"aggiunta del cluster consente di eseguire il provisioning dello storage in qualsiasi cluster.' 
---
= Aggiungere il cluster di storage a VSC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire il provisioning del primo datastore a un host ESXi nel data center, è necessario aggiungere il cluster o una specifica macchina virtuale di storage (SVM) a Virtual Storage Console per VMware vSphere. L'aggiunta del cluster consente di eseguire il provisioning dello storage su qualsiasi SVM del cluster.

.Prima di iniziare
È necessario disporre delle credenziali di amministratore per il cluster di storage o per il che si sta aggiungendo.

.A proposito di questa attività
A seconda della configurazione, il cluster potrebbe essere stato rilevato automaticamente o potrebbe essere già stato aggiunto.

.Fasi
. Accedere a vSphere Web Client.
. Selezionare *Virtual Storage Console*.
. Selezionare *Storage Systems*, quindi fare clic sull'icona *Add*.
. Nella finestra di dialogo *Aggiungi sistema di storage*, immettere il nome host e le credenziali di amministratore per il cluster di storage oppure fare clic su *OK*.

