---
permalink: nfs-config-esxi/task_configuring_esxi_host_best_practice_settings.html 
sidebar: sidebar 
keywords: ensure, esxi, practice, setting, correct, host, loss, nfs, connection, storage, configure, configure the esxi host best practice settings 
summary: 'È necessario assicurarsi che le impostazioni delle Best practice per l"host ESXi siano corrette in modo che l"host ESXi possa gestire correttamente la perdita di una connessione NFS o di uno storage.' 
---
= Configurare le impostazioni delle Best practice per l'host ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario assicurarsi che le impostazioni delle Best practice per l'host ESXi siano corrette in modo che l'host ESXi possa gestire correttamente la perdita di una connessione NFS o di uno storage.

.Fasi
. Dalla pagina iniziale di VMware vSphere Web Client, fare clic su *vCenter* > *hosts*.
. Fare clic con il pulsante destro del mouse sull'host, quindi selezionare *Actions* > *NetApp VSC* > *Set recommended values*.
. Nella finestra di dialogo *NetApp Recommended Settings* (Impostazioni consigliate NetApp), assicurarsi che tutte le opzioni siano selezionate, quindi fare clic su *OK*.
+
Le impostazioni MPIO non si applicano a NFS. Tuttavia, se si utilizzano altri protocolli, assicurarsi che tutte le opzioni siano selezionate.

+
VCenter Web Client visualizza l'avanzamento dell'attività.


