---
permalink: nfs-config-esxi/task_installing_virtual_storage_console_for_vmware_vsphere.html 
sidebar: sidebar 
keywords: configuration, provision, task, storage, esxi, host, plug-in, vcenter, server, install 
summary: Per automatizzare molte delle attività di configurazione e provisioning necessarie per utilizzare lo storage con un host ESXi. È un plug-in di vCenter Server. 
---
= Installare
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Virtual Storage Console per automatizzare molte delle attività di configurazione e provisioning necessarie per utilizzare lo storage con un host ESXi. È un plug-in di vCenter Server.

.Prima di iniziare
È necessario disporre delle credenziali di amministratore sul server vCenter utilizzato per gestire l'host ESXi.

.A proposito di questa attività
* Virtual Storage Console viene installata come appliance virtuale che include Virtual Storage Console, vStorage API for Storage Awareness (VASA) Provider e Storage Replication Adapter (SRA) per le funzionalità di VMware vSphere.


.Fasi
. Scaricare la versione di supportata per la configurazione, come mostrato nello strumento matrice di interoperabilità.
+
https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"]

. Implementare l'appliance virtuale e configurarla seguendo la procedura descritta nella _Guida all'installazione e all'implementazione_.

