---
permalink: fc-config-rhel/index.html 
sidebar: sidebar 
keywords: fc, service, storage, virtual, machine, svm, provision, lun, fc, host, bus, adapter, hba, linux, server, configuration, red hat enterprise linux 
summary: È possibile configurare rapidamente il servizio FC su una macchina virtuale di storage, eseguire il provisioning di un LUN e rendere disponibile il LUN utilizzando un adattatore bus host FC su un server Red Hat Enterprise Linux. 
---
= Panoramica della configurazione FC per Red Hat Enterprise Linux
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare rapidamente il servizio FC su una macchina virtuale di storage (SVM), eseguire il provisioning di un LUN e rendere disponibile il LUN utilizzando un HBA (host bus adapter) FC su un server Red Hat Enterprise Linux utilizzando l'interfaccia classica di Gestore di sistema ONTAP (ONTAP 9.7 e versioni precedenti).

Utilizzare questa procedura per impostare il servizio FC su una SVM se:

* L'host esegue una versione supportata di Red Hat Enterprise Linux 6.4 o successiva.
* Si utilizzano HBA e switch FC tradizionali.
+

NOTE: Fibre Channel over Ethernet (FCoE) non è trattato in questa procedura.

* Sono disponibili almeno due porte di destinazione FC su ciascun nodo del cluster.
Le porte FC e UTA2 integrate (dette anche "`CNA`"), così come alcuni adattatori, sono configurabili. La configurazione di queste porte viene eseguita nell'interfaccia della riga di comando (CLI) di ONTAP e non viene trattata in questa procedura.
* Non si sta configurando l'avvio FC SAN.


Se questi presupposti non sono corretti per la situazione, dovresti vedere le seguenti risorse:

* https://docs.netapp.com/us-en/ontap/san-admin/index.html["Amministrazione SAN"^]
* https://docs.netapp.com/us-en/ontap/san-config/index.html["Configurazione SAN"^]
* https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html["Installazione di Linux Unified host Utilities 7.1"^]




== Altri modi per farlo in ONTAP

|===


| Per eseguire queste attività con... | Fare riferimento a... 


| System Manager riprogettato (disponibile con ONTAP 9.7 e versioni successive) | link:https://docs.netapp.com/us-en/ontap/task_san_provision_linux.html["Eseguire il provisioning dello storage SAN per i server Linux"^] 


| Interfaccia a riga di comando (CLI) di ONTAP | link:https://docs.netapp.com/us-en/ontap/san-admin/lun-setup-workflow-concept.html["Workflow di setup del LUN con la CLI"^] 
|===