---
permalink: fc-config-rhel/task_verifying_that_iscsi_fc_configuration_is_supported.html 
sidebar: sidebar 
keywords: reliable, operation, verify, entire, fc, configuration, support, verify that the fc configuration is supported 
summary: 'Per un funzionamento affidabile, è necessario verificare che l"intera configurazione FC sia supportata.' 
---
= Verificare che la configurazione FC sia supportata
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per un funzionamento affidabile, è necessario verificare che l'intera configurazione FC sia supportata.

.Fasi
. Accedere alla matrice di interoperabilità per verificare di disporre di una combinazione supportata dei seguenti componenti:
+
** Software ONTAP
** Architettura della CPU del computer host (per server rack standard)
** Modello specifico di blade del processore (per server blade)
** Modello e versioni di driver, firmware e BIOS di HBA (host bus adapter) FC
** Protocollo storage (FC)
** Versione del sistema operativo Linux
** Pacchetto DM-multipath
** Utility host unificate Linux


. Selezionare il nome della configurazione selezionata.
+
I dettagli della configurazione vengono visualizzati nella finestra Dettagli configurazione.

. Esaminare le informazioni nelle seguenti schede:
+
** Note
+
Elenca avvisi e informazioni importanti specifici della configurazione.

+
Esaminare gli avvisi per identificare i pacchetti richiesti per il sistema operativo in uso.

** Policy e linee guida
+
Fornisce linee guida generali per tutte le configurazioni SAN.




