---
permalink: fc-config-rhel/task_installing_linux_unified_host_utilities_optimizing_i_o_performance.html 
sidebar: sidebar 
keywords: linux, unified, host, utilities, software, sanlun, utility, netapp, lun, report, tool, display, information, storage, cluster, node, bus, adapter, hba, correct, server, profile, linux, optimize, performance, install linux unified host utilities and optimize i/o performance 
summary: 'Il software Linux Unified host Utilities include l"utility sanlun, uno strumento di reporting del LUN NetApp che è possibile utilizzare per visualizzare informazioni sui nodi del cluster di storage e sugli host Bus Adapter presenti sull"host Linux.' 
---
= Installare Linux Unified host Utilities e ottimizzare le performance di i/O.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il software Linux Unified host Utilities include `sanlun` Utility, uno strumento di reporting del LUN NetApp che consente di visualizzare informazioni sul nodo del cluster di storage e gli HBA (host Bus Adapter) presenti sull'host Linux. Per ottimizzare le performance dello storage NetApp, è inoltre necessario abilitare il profilo server corretto sull'host Linux.

.Prima di iniziare
È necessario aver identificato la versione supportata delle utility host unificate Linux per la configurazione utilizzando la matrice di interoperabilità. È inoltre necessario disporre di `tuned` Che fa parte della distribuzione del sistema operativo Linux e contiene `tuned-adm` che consente di impostare il profilo del server sull'host.

.Fasi
. Scaricare la versione supportata di Linux Unified host Utilities dal NetApp Support Site.
+
http://mysupport.netapp.com/NOW/cgi-bin/software["Download NetApp: Software"]

. Installare il software Linux Unified host Utilities seguendo le istruzioni nella documentazione di installazione.
. Se il `tuned` il pacchetto non è installato, immettere il seguente comando:``yum install tuned``
. Per un host fisico, assicurarsi di aver impostato `enterprise-storage` profilo: `tuned-adm profile enterprise-storage`
. Per un host virtuale, assicurarsi di aver impostato `virtual-guest` profilo: `tuned-adm profile virtual-guest`
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["Installazione di Linux Unified host Utilities 7.1"]


