---
permalink: fc-config-rhel/task_deciding_where_to_provision_volume.html 
sidebar: sidebar 
keywords: provision, volume, contain, lun, exist, storage, virtual, machine, svm, create, fc, exist, decide where to provision the volume 
summary: Prima di eseguire il provisioning di un volume per contenere le LUN, è necessario decidere se aggiungere il volume a una macchina virtuale di storage esistente o creare una nuova SVM per il volume. Potrebbe essere necessario configurare FC anche su una SVM esistente. 
---
= Decidere dove eseguire il provisioning del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire il provisioning di un volume per contenere le LUN, è necessario decidere se aggiungere il volume a una SVM (Storage Virtual Machine) esistente o se creare una nuova SVM per il volume. Potrebbe essere necessario configurare FC anche su una SVM esistente.

.A proposito di questa attività
Se una SVM esistente è già configurata con i protocolli necessari e dispone di LIF accessibili dall'host, è più semplice utilizzare la SVM esistente.

È possibile creare una nuova SVM per separare i dati o l'amministrazione da altri utenti del cluster di storage. Non c'è alcun vantaggio nell'utilizzo di SVM separate solo per separare protocolli diversi.



== Procedura

* Se si desidera eseguire il provisioning dei volumi su una SVM già configurata per FC, verificare che il servizio FC sia in esecuzione e creare un LUN sulla SVM.
+
link:task_verifying_that_fc_service_is_running_on_existing_svm.html["Verificare che il servizio FC sia in esecuzione su una SVM esistente"]

+
link:task_creating_lun_its_containing_volume.html["Creazione di un LUN"]

* Se si desidera eseguire il provisioning di volumi su una SVM esistente con FC abilitato ma non configurato, configurare iSCSI sulla SVM esistente.
+
link:task_configuring_iscsi_fc_creating_lun_on_existing_svm.html["Configurazione di FC su una SVM esistente"]

+
Questo è il caso se non si è seguita questa procedura per creare SVM durante la configurazione di un protocollo diverso.

* Se si desidera eseguire il provisioning dei volumi su una nuova SVM, creare la SVM.
+
link:task_creating_svm.html["Creazione di una nuova SVM"]


