---
permalink: fc-config-rhel/task_verifying_that_host_can_write_to_read_fom_lun.html 
sidebar: sidebar 
keywords: multipath, device, verify, host, write, data, verify that the host can write to and read from a multipath device 
summary: 'Prima di utilizzare un dispositivo multipath, verificare che l"host possa scrivere i dati sul dispositivo multipath e leggerli.' 
---
= Verificare che l'host sia in grado di scrivere e leggere da un dispositivo multipath
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di utilizzare un dispositivo multipath, verificare che l'host possa scrivere i dati sul dispositivo multipath e leggerli.

.Prima di iniziare
DM-multipath deve essere configurato sull'host Linux per i nodi del cluster di storage a cui si accede.

.A proposito di questa attività
Se il nodo del cluster di storage a cui corrisponde il dispositivo multipath può essere eseguito il failover nel nodo partner, è necessario verificare la lettura dei dati mentre si verifica il failover del nodo. Questa verifica potrebbe non essere possibile se il cluster di storage è in uso in produzione.

.Fasi
. Eseguire alcuni i/o sul dispositivo multipath specificato:
+
`dd if=/dev/zero of=<multipath_device_name\>`

. Verificare che l'i/o sia in esecuzione sul dispositivo multipath, specificando il numero di secondi per aggiornare le statistiche (ad esempio, ogni due secondi, come mostrato):
+
`iostat 2`

+
Quando l'i/o è in esecuzione sul dispositivo multipath, è possibile vedere i vari contatori di i/o in uscita cambiare dinamicamente, indicando che l'i/o è in esecuzione correttamente sul dispositivo multipath.

+
[listing]
----
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
            0.00    0.00    0.01    0.00    0.00   99.98

Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
sda               0.18         1.34         2.29     832606    1428026
dm-0              0.37         1.29         2.29     801530    1427984
dm-1              0.00         0.00         0.00       2576          0
dm-2              0.00         0.00         0.00       1770         24
sdd               0.17         1.18        17.87     734688   11128584
sde               0.17         1.18        18.01     734560   11219016
sdf               0.00         0.00         0.00       1344          0
sdg               0.00         0.00         0.00       1344          0
dm-3              0.68         4.71        71.96    2932496   44816008
sdh               0.17         1.18        18.22     734360   11343920
sdi               0.17         1.18        17.86     734272   11124488
sdj               0.00         0.00         0.00       1344          0
sdk               0.00         0.00         0.00       1344          0
.............
----
. Se possibile, eseguire `takeover` comando sul nodo del cluster di storage:
+
`storage failover takeover -ofnode <node_name\>`

. Verificare che i/o sia ancora in esecuzione sul dispositivo multipath rieseguendo``iostat`` comando.
. Eseguire `giveback` comando sul nodo del cluster di storage:
+
`storage failover giveback -ofnode <node_name\>`

. Controllare `iostat` Output per verificare che i/o sia ancora in esecuzione.




== Cosa fare in seguito

Se uno qualsiasi dei test ha esito negativo, verificare che il servizio FC sia in esecuzione e controllare nuovamente la configurazione del percorso multiplo DM e i percorsi FC verso il dispositivo multipath.
