---
permalink: iscsi-config-rhel/index.html 
sidebar: sidebar 
keywords: iscsi, service, storage, virtual, machine, svm, lun, initiator, red, hat, enterprise, linux, server, configuration, san, provision, provisioning 
summary: Queste procedure descrivono come configurare rapidamente il servizio iSCSI su una macchina virtuale di storage, eseguire il provisioning di un LUN e rendere disponibile il LUN utilizzando un iSCSI Initiator su un server Red Hat Enterprise Linux. 
---
= Panoramica della configurazione iSCSI per Red Hat Enterprise Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzando l'interfaccia classica di Gestore di sistema ONTAP (ONTAP 9.7 e versioni precedenti), è possibile configurare rapidamente il servizio iSCSI su una macchina virtuale di storage (SVM), eseguire il provisioning di un LUN e rendere il LUN disponibile su un server Red Hat Enterprise Linux.

Queste procedure si basano sui seguenti presupposti:

* Si sta utilizzando iSCSI software Initiator su un host Red Hat Enterprise Linux con una versione supportata di RHEL Series 6.4 o superiore.
* La rete utilizza l'indirizzamento IPv4.
* Si desidera assegnare gli indirizzi alle interfacce logiche utilizzando uno dei seguenti metodi:
+
** Automaticamente, da una subnet definita
** Manualmente, utilizzando un indirizzo selezionato da una subnet esistente
** Manualmente, utilizzando un indirizzo che verrà aggiunto a una subnet esistente


* Non si sta configurando l'avvio SAN iSCSI.


Per ulteriori informazioni su come configurare l'host specifico con ONTAP, vedere https://docs.netapp.com/us-en/ontap-sanhost/index.html["Configurazione host SAN ONTAP"].

Per ulteriori informazioni sull'amministrazione SAN, consultare https://docs.netapp.com/us-en/ontap/san-admin/index.html["Panoramica sull'amministrazione DELLA SAN ONTAP 9"]



== Altri modi per farlo in ONTAP

|===


| Per completare questa attività utilizzando... | Fare riferimento a... 


| System Manager riprogettato (disponibile con 9.7 e versioni successive) | https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Eseguire il provisioning dello storage SAN"^] 


| Interfaccia a riga di comando (CLI) di ONTAP | https://docs.netapp.com/us-en/ontap/san-admin/lun-setup-workflow-concept.html["Workflow di setup del LUN con la CLI"^] 
|===