---
permalink: iscsi-config-rhel/task_discovering_new_scsi_devices_dm_multipath_devices.html 
sidebar: sidebar 
keywords: 'lun, storage, cluster, linux, scsi, device, i/o, path, dm-multipath, multipath, manual, discover new scsi devices (luns) and multipath devices' 
summary: 'I LUN del cluster di storage appaiono all"host Linux come dispositivi SCSI, che sono percorsi di i/o che DM-multipath aggrega in un nuovo dispositivo, chiamato dispositivo multipath. L"host non rileva automaticamente i nuovi dispositivi SCSI (LUN) aggiunti al sistema. È necessario eseguire una nuova scansione manuale per rilevarli.' 
---
= Rilevare nuovi dispositivi SCSI (LUN) e multipath
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I LUN del cluster di storage appaiono all'host Linux come dispositivi SCSI, che sono percorsi di i/o che DM-multipath aggrega in un nuovo dispositivo, chiamato dispositivo multipath. L'host non rileva automaticamente i nuovi dispositivi SCSI (LUN) aggiunti al sistema. È necessario eseguire una nuova scansione manuale per rilevarli.

.Prima di iniziare
È necessario disporre di una copia di `rescan` script, che si trova in `sg3_utils` Pacchetto che fa parte della distribuzione del sistema operativo Linux.

.Fasi
. Individuare i nuovi dispositivi SCSI (LUN) e creare i corrispondenti dispositivi multipath per i LUN:
+
`/usr/bin/rescan-scsi-bus.sh`

. Verificare la configurazione di DM-multipath:
+
`multipath -ll`

+
Viene visualizzato il seguente tipo di output, che elenca le impostazioni consigliate per ogni LUN NetApp:

+
[listing]
----
3600a0980324666546e2b443251655177 dm-2 NETAPP,LUN C-Mode
size=10G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 0:0:1:0 sdb 8:16  active ready  running
| |- 0:0:0:0 sda 8:0   active ready  running
| |- 1:0:0:0 sde 8:64  active ready  running
| `- 1:0:1:0 sdf 8:80  active ready  running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 0:0:3:0 sdd 8:48  active ready  running
  |- 1:0:3:0 sdh 8:112 active ready  running
  |- 0:0:2:0 sdc 8:32  active ready  running
  `- 1:0:2:0 sdg 8:96  active ready  running
----

