---
permalink: volume-disaster-recovery/index.html 
sidebar: sidebar 
keywords: content, destination, activate, volume, disaster, reactivate, source, ontap, volume disaster recovery overview 
summary: 'È possibile attivare rapidamente un volume di destinazione dopo un disastro e quindi riattivare il volume di origine in ONTAP utilizzando l"interfaccia classica di Gestore di sistema di ONTAP (ONTAP 9.7 e versioni precedenti).' 
---
= Panoramica sul disaster recovery dei volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile attivare rapidamente un volume di destinazione dopo un disastro e quindi riattivare il volume di origine in ONTAP utilizzando l'interfaccia classica di Gestore di sistema di ONTAP (ONTAP 9.7 e versioni precedenti).

Utilizzare questa procedura se si desidera eseguire il disaster recovery a livello di volume nel modo seguente:

* Stai lavorando con cluster che eseguono ONTAP 9.
* Sei un amministratore del cluster.
* Di seguito è stata configurata la relazione SnapMirror xref:../volume-disaster-prep/index.html[Preparazione al disaster recovery dei volumi]
* L'amministratore del cluster di origine ha dichiarato che i dati nel volume di origine non sono disponibili a causa di eventi come l'infezione da virus che ha portato alla corruzione dei dati o all'eliminazione accidentale dei dati.
* Si desidera utilizzare Gestione sistema, non l'interfaccia della riga di comando di ONTAP o uno strumento di scripting automatico.
* Si desidera utilizzare l'interfaccia classica di Gestione sistema per ONTAP 9.7 e versioni precedenti, non l'interfaccia utente di Gestione sistema di ONTAP per ONTAP 9.7 e versioni successive.
* Si desidera utilizzare le Best practice, non esplorare tutte le opzioni disponibili.
* Non si desidera leggere un sacco di background concettuale.




== Altri modi per farlo in ONTAP

[cols="2"]
|===
| Per eseguire queste attività con... | Guarda questo contenuto... 


| System Manager riprogettato (disponibile con ONTAP 9.7 e versioni successive) | link:https://docs.netapp.com/us-en/ontap/task_dp_serve_data_from_destination.html["Fornire i dati da una destinazione SnapMirror"^] 


| L'interfaccia della riga di comando di ONTAP | link:https://docs.netapp.com/us-en/ontap/data-protection/make-destination-volume-writeable-task.html["Attivare il volume di destinazione"^] 
|===