---
permalink: smb-config/task_deciding_where_to_provision_new_volume.html 
sidebar: sidebar 
keywords: create, cifs, volume, place, exist, storage, virtual, machine, svm, configuration, require, decision, workflow, decide where to provision the new volume 
summary: 'Prima di creare un nuovo volume CIFS, è necessario decidere se posizionarlo in una macchina virtuale di storage (SVM) esistente e, in tal caso, quanta configurazione richiede SVM. Questa decisione determina il tuo flusso di lavoro.' 
---
= Decidere dove eseguire il provisioning del nuovo volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di creare un nuovo volume CIFS, è necessario decidere se posizionarlo in una macchina virtuale di storage (SVM) esistente e, in tal caso, quanta configurazione richiede SVM. Questa decisione determina il tuo flusso di lavoro.



== Procedura

* Crea una nuova SVM abilitata per CIFS per il provisioning di un volume su una nuova SVM
+
link:task_creating_protocol_enabled_svm.html["Creazione di una nuova SVM abilitata per CIFS"]

+
Devi scegliere questa opzione se CIFS non è abilitato su una SVM esistente.

* Se si desidera eseguire il provisioning di un volume su una SVM esistente in cui CIFS è attivato ma non configurato, configurare l'accesso CIFS/SMB sulla SVM esistente.
+
link:task_configuring_access_to_existing_svm.html["Configurazione dell'accesso CIFS/SMB su una SVM esistente"]

+
Scegliere questa opzione se si è utilizzata la procedura per creare SVM per l'accesso SAN.

* Se si desidera eseguire il provisioning di un volume su una SVM esistente completamente configurata per l'accesso CIFS, aggiungere un volume CIFS alla SVM abilitata per CIFS.
+
link:concept_adding_protocol_volume_to_protocol_enabled_svm.html["Aggiunta di un volume CIFS a una SVM abilitata per CIFS"]


