---
permalink: fc-config-windows/index.html 
sidebar: sidebar 
keywords: describe, fc, service, storage virtual machine, svm, provision, lun, hba, windows, host 
summary: È possibile configurare rapidamente il servizio FC su una macchina virtuale di storage, eseguire il provisioning di un LUN e rendere disponibile il LUN utilizzando un HBA FC su un computer host Windows. 
---
= Panoramica della configurazione FC per Windows
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare rapidamente il servizio FC su una macchina virtuale di storage (SVM), eseguire il provisioning di un LUN e rendere disponibile il LUN utilizzando un HBA FC su un computer host Windows con l'interfaccia classica di Gestore di sistema ONTAP (ONTAP 9.7 e versioni precedenti).

Utilizzare questa procedura per impostare il servizio FC su una SVM se:

* Si utilizzano HBA e switch FC tradizionali.


Questa procedura non copre le situazioni in cui:

* Sono disponibili almeno due porte di destinazione FC su ciascun nodo del cluster.
FC e UTA2 integrati (anche denominati `CNA`) e alcuni adattatori sono configurabili. La configurazione di queste porte viene eseguita nell'interfaccia utente di ONTAP e non viene trattata in questa procedura.
* Non si sta configurando l'avvio FC SAN.
* Non si utilizza il VFC (Virtual Fibre Channel) con guest Hyper-V o ESX.




== Altri modi per farlo in ONTAP

|===


| Per eseguire queste attività con... | Fare riferimento a... 


| System Manager riprogettato (disponibile con ONTAP 9.7 e versioni successive) | link:https://docs.netapp.com/us-en/ontap/task_san_provision_windows.html["Eseguire il provisioning dello storage SAN per i server Windows"^] 


| Interfaccia a riga di comando (CLI) di ONTAP | link:https://docs.netapp.com/us-en/ontap/san-admin/lun-setup-workflow-concept.html["Workflow di setup del LUN con la CLI"^] 
|===
.Risorse aggiuntive
* https://docs.netapp.com/us-en/ontap-sanhost/index.html["Documentazione NetApp: Utility host"^]

