---
permalink: nas-multiprotocol-config/task_verifying_nfs_access_from_unix_administration_host.html 
sidebar: sidebar 
keywords: configure, nfs, access, storage, virtual, machine, svm, configuration, administration, host, read, data, verify, verify nfs access from a unix administration host 
summary: 'Dopo aver configurato l"accesso NFS alla macchina virtuale di storage (SVM), è necessario verificare la configurazione accedendo a un host di amministrazione NFS e leggendo i dati da e scrivendo i dati su SVM.' 
---
= Verificare l'accesso NFS da un host di amministrazione UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver configurato l'accesso NFS alla macchina virtuale di storage (SVM), è necessario verificare la configurazione accedendo a un host di amministrazione NFS e leggendo i dati da e scrivendo i dati su SVM.

.Prima di iniziare
* Il sistema client deve disporre di un indirizzo IP consentito dalla regola di esportazione specificata in precedenza.
* È necessario disporre delle informazioni di accesso per l'utente root.


.Fasi
. Accedere come utente root al sistema client.
. Invio `cd /mnt/` per modificare la directory nella cartella mount.
. Creare e montare una nuova cartella utilizzando l'indirizzo IP di SVM:
+
.. Invio `mkdir /mnt/folder` per creare una nuova cartella.
.. Invio `mount -t nfs -o nfsvers=3,hard IPAddress:/volume_name /mnt/folder` per montare il volume in questa nuova directory.
.. Invio `cd folder` per modificare la directory nella nuova cartella.
+
I seguenti comandi creano una cartella denominata test1, montano il volume vol1 all'indirizzo IP 192.0.2.130 sulla cartella di montaggio test1 e cambiano nella nuova directory test1:

+
[listing]
----
host# mkdir /mnt/test1
host# mount -t nfs -o nfsvers=3,hard 192.0.2.130:/vol1 /mnt/test1
host# cd /mnt/test1
----


. Creare un nuovo file, verificarne l'esistenza e scriverne del testo:
+
.. Invio `touch filename` per creare un file di test.
.. Invio `ls -l filename` per verificare l'esistenza del file.
.. Invio `cat >filename`, Digitare del testo, quindi premere Ctrl+D per scrivere il testo nel file di prova.
.. Invio `cat filename` per visualizzare il contenuto del file di test.
.. Invio `rm filename` per rimuovere il file di test.
.. Invio `cd ..` per tornare alla directory principale.


+
[listing]
----
host# touch myfile1
host# ls -l myfile1
-rw-r--r-- 1 root root 0 Sep 18 15:58 myfile1
host# cat >myfile1
This text inside the first file
host# cat myfile1
This text inside the first file
host# rm -r myfile1
host# cd ..
----


.Risultati
Hai confermato di aver attivato l'accesso NFS a SVM.
