---
permalink: expansion/concept_configuring_node_management_lifs.html 
sidebar: sidebar 
keywords: controller, module, physical, install, power, configure, node-mangement, lif, configure node-management lifs 
summary: Una volta installati fisicamente i moduli controller, è possibile accenderli e configurarne la LIF di gestione dei nodi. 
---
= Configurare le LIF di gestione dei nodi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una volta installati fisicamente i moduli controller, è possibile accenderli e configurarne la LIF di gestione dei nodi.

.A proposito di questa attività
Eseguire questa procedura su entrambi i nodi.

.Fasi
. Accedere al modulo controller tramite la console seriale.
. Accendere il modulo controller e attendere l'avvio del nodo e l'avvio automatico della procedura guidata di configurazione del cluster sulla console.
+
[listing]
----
Welcome to the cluster setup wizard.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the cluster setup wizard.
   Any changes you made before quitting will be saved.

You can return to cluster setup at any time by typing "cluster setup".
To accept a default or omit a question, do not enter a value.
----
. Seguire le istruzioni della procedura guidata di installazione del cluster basata su Web per configurare una LIF di gestione dei nodi utilizzando le informazioni di rete raccolte in precedenza.
. Tipo `exit` Una volta completata la configurazione LIF di gestione dei nodi, uscire dall'installazione guidata e completare le attività di amministrazione.
+
[listing]
----
Use your web browser to complete cluster setup by accessing
https://10.63.11.29

Otherwise, press Enter to complete cluster setup using the command line interface:
exit
----
. Accedere al nodo come `admin` utente, che non richiede una password.
+
[listing]
----
Tue Mar 4 23:13:33 UTC 2015
login: admin
******************************************************
* This is a serial console session. Output from this *
* session is mirrored on the SP console session.     *
----
. Ripetere l'intera procedura per il secondo modulo controller appena installato.

