---
permalink: expansion/task_backing_up_cluster_configuration.html 
sidebar: sidebar 
keywords: expand, cluster, advance, privilege, backup, file, configuration, information, back up the cluster configuration 
summary: Prima di espandere un cluster, è necessario utilizzare il privilegio avanzato per creare un file di backup per salvare le informazioni di configurazione del cluster e, facoltativamente, salvare le configurazioni del nodo. 
---
= Eseguire il backup della configurazione del cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di espandere un cluster, è necessario utilizzare il privilegio avanzato per creare un file di backup per salvare le informazioni di configurazione del cluster e, facoltativamente, salvare le configurazioni del nodo.

.Fasi
. Impostare il livello di privilegio su Advanced (avanzato) utilizzando `set -privilege advanced` comando.
. Creare un file di backup della configurazione del cluster utilizzando `system configuration backup create` con il `-backup-type cluster` parametro.
+
[listing]
----
cluster1::*> system configuration backup create -node cluster1-1 -backup-name clusterbeforeexpansion.7z -backup-type cluster
[Job 5573] Job is queued: Cluster Backup OnDemand Job.
----
. Creare un file di backup della configurazione di ciascun nodo utilizzando `system configuration backup create` con il `-backup-type node` parametro per ogni nodo.
. Restituire il livello di privilegio ad admin utilizzando `set -privilege admin` comando.

