---
permalink: volume-restore-snapvault/task_verifying_restore_operation.html 
sidebar: sidebar 
keywords: perform, restore, operation, snapvault, backup, destination, volume, verify, source cluster, verify the restore operation 
summary: 'Dopo aver eseguito l"operazione di ripristino dal volume di destinazione del backup di SnapVault, è necessario verificare lo stato dell"operazione di ripristino sul cluster di origine.' 
---
= Verificare l'operazione di ripristino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver eseguito l'operazione di ripristino dal volume di destinazione del backup di SnapVault, è necessario verificare lo stato dell'operazione di ripristino sul cluster di origine.

.A proposito di questa attività
È necessario eseguire questa attività dal cluster *source*.

.Fasi
. Accedere alla finestra *Volumes*.
. Selezionare il volume di origine nell'elenco Volumes (volumi) ed eseguire una delle seguenti operazioni, a seconda della versione di ONTAP in uso:
+
** A partire da ONTAP 9.3: Fare doppio clic sul volume di origine per visualizzare i dettagli, quindi fare clic su *PROTECTION* per identificare il volume di destinazione nella relazione di SnapMirror e il nome della SVM che contiene il volume.
** ONTAP 9.2 o versioni precedenti: Fare clic sulla scheda inferiore *protezione dati* per identificare il volume di destinazione nella relazione SnapMirror e il nome della SVM che contiene il volume.
Viene visualizzato il campo Type (tipo) `Restore` temporaneamente. Al termine dell'operazione di ripristino, viene visualizzato il campo `Vault`.
+
È necessario risolvere eventuali problemi nelle relazioni SnapVault. Le procedure di troubleshooting per le relazioni di SnapMirror sono applicabili anche alle relazioni di SnapVault.

+
http://www.netapp.com/us/media/tr-4015.pdf["Report tecnico di NetApp 4015: Configurazione e Best practice di SnapMirror per ONTAP 9.1, 9.2"^]




