---
permalink: nfs-config/index.html 
sidebar: sidebar 
keywords: nfs, access, volume, exist, storage, virtual, machine, svm, system manager classic 
summary: 'È possibile configurare rapidamente l"accesso NFS a un nuovo volume su una macchina virtuale di storage (SVM) nuova o esistente utilizzando l"interfaccia classica di Gestore di sistema di ONTAP (ONTAP 9.7 e versioni precedenti).' 
---
= Panoramica della configurazione di NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare rapidamente l'accesso NFS a un nuovo volume su una macchina virtuale di storage (SVM) nuova o esistente utilizzando l'interfaccia classica di Gestore di sistema di ONTAP (ONTAP 9.7 e versioni precedenti).

Utilizzare questa procedura per configurare l'accesso a un volume nel modo seguente:

* L'accesso NFS avviene tramite NFSv3, non NFSv4 o NFSv4.1.
* Si desidera utilizzare le Best practice, non esplorare tutte le opzioni disponibili.
* La rete dati utilizza l'IPSpace predefinito, il dominio di trasmissione predefinito e il gruppo di failover predefinito.
+
Se la rete dati è piatta, l'utilizzo di questi oggetti predefiniti garantisce il corretto failover delle LIF in caso di errore di collegamento. Se non si utilizzano gli oggetti predefiniti, fare riferimento a. https://docs.netapp.com/us-en/ontap/networking/index.html["Documentazione sulla gestione di rete"^] Per informazioni su come configurare il failover del percorso LIF.

* Per proteggere il nuovo volume verranno utilizzate le autorizzazioni per i file UNIX.
* LDAP, se utilizzato, viene fornito da Active Directory.


Per informazioni sulla gamma delle funzionalità del protocollo NFS di ONTAP, consulta link:https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["Panoramica di riferimento di NFS"^].



== Altri modi per farlo in ONTAP

|===


| Per eseguire queste attività con... | Fare riferimento a... 


| System Manager riprogettato (disponibile con ONTAP 9.7 e versioni successive) | link:https://docs.netapp.com/us-en/ontap/task_nas_provision_linux_nfs.html["Provisioning dello storage NAS per i server Linux utilizzando NFS"^] 


| L'interfaccia della riga di comando di ONTAP | link:https://docs.netapp.com/us-en/ontap/nfs-config/index.html["Panoramica della configurazione di NFS con la CLI"^] 
|===